Removing credsSecret required field in tenant spec
minio/operator pull request #1009
Opened 2022-02-05 22:41 UTC by Alevsk

- Removing required credsSecret field in tenant spec
- Migration from creddsSecret to Configuration field for old tenants

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2022-02-06 07:15 UTC, harshavardhana requested changes

2022-02-06 07:15 UTC, harshavardhana commented on pkg/controller/cluster/main-controller.go
> +
Do not check for upgrades without validating the tenant spec. @Alevsk

2022-02-06 07:15 UTC, harshavardhana commented on pkg/controller/cluster/upgrades.go
> +}
We should perhaps do this for v4.4.8 -made a new release to make sure to fix an important bug during deployment.

2022-02-06 07:15 UTC, harshavardhana commented on examples/kustomization/tenant-test/tenantNamePatch.yaml
> +  value: storage-test
add a missing newline

2022-02-06 07:15 UTC, harshavardhana commented on examples/kustomization/tenant-test/tenant-credssecret.yaml
> +type: Opaque
add a missing newline

2022-02-06 07:15 UTC, harshavardhana commented on examples/kustomization/tenant-test/kustomization.yaml
> +    path: tenantNamePatch.yaml
add a missing newline

2022-02-08 01:33 UTC, harshavardhana submitted a review, later dismissed

2022-03-01 01:14 UTC, harshavardhana approved these changes

2022-03-13 05:05 UTC, harshavardhana requested changes

2022-03-13 05:05 UTC, harshavardhana commented on kubectl-minio/cmd/resources/secret.go
> +	m["MINIO_BROWSER"] = "on"
```suggestion
```

This is always `on` by default no need to explicitly set this.

2022-04-05 21:42 UTC, harshavardhana approved these changes

2022-05-11 18:56 UTC, harshavardhana commented
PTAL @Alevsk at conflicts

2022-05-29 09:48 UTC, harshavardhana commented
Can we rebase this and take it in @Alevsk ?

2022-05-31 22:32 UTC, Alevsk commented
> Can we rebase this and take it in @Alevsk ?

Working on this today @harshavardhana

2022-06-28 04:55 UTC, harshavardhana requested changes
LGTM overall, few comments

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/upgrades.go
> +	tenantConfiguration["MINIO_BROWSER"] = "on"
```suggestion
```
This is default doesn't need to be set explicitly.

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/upgrades.go
> +		return nil, fmt.Errorf("'%s/%s' Error migrating tenant credsSecret to Configuration", tenant.Namespace, tenant.Name)
```suggestion
		return nil, fmt.Errorf("accessKey/secretKey are empty - '%s/%s' error in migrating tenant credsSecret to newer configuration", tenant.Namespace, tenant.Name)
```

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/upgrades.go
> +		return nil, fmt.Errorf("'%s/%s' Error migrating tenant credsSecret, credsSecret not present", tenant.Namespace, tenant.Name)
```suggestion
		return nil, fmt.Errorf("'%s/%s' error migrating tenant credsSecret, credsSecret does not exist", tenant.Namespace, tenant.Name)
```

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/upgrades.go
> +		klog.Errorf("Error updating tenant '%s/%s', could not update tenant.spec.configuration field: %v", tenant.Namespace, tenant.Name, err)
return error here

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/main-controller.go
> +		klog.Errorf("Error instantiating adminClnt: %v", err)
```suggestion
		klog.Errorf("Error initializing minio admin client: %v", err)
```

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/main-controller.go
> +		if _, err = c.updateTenantStatus(ctx, tenant, StatusTenantCredentialsNotSet, 0); err != nil {
```suggestion
		if _, err = c.updateTenantStatus(ctx, tenant, StatusTenantCredentialsNotSet, 0); err != nil {
```
This error shadows the error returned by `tenant.NewMinIOAdmin()` leading to the err being `nil` 

Instead you should use a newer variable such as `uerr` or something.

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/main-controller.go
> +		if _, err = c.updateTenantStatus(ctx, tenant, StatusTenantCredentialsNotSet, 0); err != nil {
```suggestion
		if _, uerr := c.updateTenantStatus(ctx, tenant, StatusTenantCredentialsNotSet, 0); uerr != nil {
```

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/main-controller.go
> +			return err
```suggestion
			return uerr
```

2022-06-28 04:55 UTC, harshavardhana commented on pkg/controller/cluster/main-controller.go
> +	StatusTenantCredentialsNotSet            = "Credentials for tenant not properly set"
```suggestion
	StatusTenantCredentialsNotSet            = "Tenant credentials are not set properly"
```

2022-06-28 04:55 UTC, harshavardhana commented on pkg/apis/minio.min.io/v2/helper.go
> +		return errors.New("please set Configuration secret with credentials for Tenant")
```suggestion
		return errors.New("please set 'configuration' secret with credentials for Tenant")
```

2022-06-28 04:55 UTC, harshavardhana commented on pkg/apis/minio.min.io/v1/helper.go
> +		return errors.New("please set configuration secret with credentials for Tenant")
```suggestion
		return errors.New("please set 'configuration' secret with credentials for Tenant")
```

2022-06-28 22:34 UTC, harshavardhana approved these changes

2022-07-19 17:55 UTC, harshavardhana commented
We should take this perhaps before v4.4.26 @dvaldivia @cniackz ?

2022-07-20 05:11 UTC, harshavardhana commented
>  We should take this perhaps before v4.4.26 @dvaldivia @cniackz ?

ping @cniackz @dvaldivia

2022-07-20 19:00 UTC, harshavardhana approved these changes

2022-08-09 17:46 UTC, cniackz commented
@Alevsk please review conflicts when you have a chance.

2022-08-09 17:47 UTC, cniackz reviewed
@Alevsk please resolve the conflicts 👍

2022-08-25 01:39 UTC, Alevsk commented
> I'm hitting an NPE with a tenant which has no config file
> 
> ```
> goroutine 361 [running]:
> k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x4dd574})
>     k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:55 +0xd8
> panic({0x16ad080, 0x2759220})
>     runtime/panic.go:1038 +0x215
> k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000294250})
>     k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:55 +0xd8
> panic({0x16ad080, 0x2759220})
>     runtime/panic.go:1038 +0x215
> github.com/minio/operator/pkg/controller/cluster.(*Controller).checkForUpgrades(0xc000450480, {0x1af9218, 0xc000042028}, 0xc000e5f180)
>     github.com/minio/operator/pkg/controller/cluster/upgrades.go:93 +0xaca
> github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc000450480, {0xc001235bc0, 0x17})
>     github.com/minio/operator/pkg/controller/cluster/main-controller.go:650 +0x5ab
> github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x163e060, 0xc000294250})
>     github.com/minio/operator/pkg/controller/cluster/main-controller.go:560 +0x245
> github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc000450480)
>     github.com/minio/operator/pkg/controller/cluster/main-controller.go:572 +0x62
> github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0x0)
>     github.com/minio/operator/pkg/controller/cluster/main-controller.go:512 +0x70
> k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fe77453cd60)
>     k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x67
> k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0003e90e0, {0x1acbfc0, 0xc0006f4e70}, 0x1, 0xc00008f620)
>     k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0xb6
> k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000998520, 0x3b9aca00, 0x0, 0x28, 0xc0003e9140)
>     k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x89
> k8s.io/apimachinery/pkg/util/wait.Until(0xc000998590, 0xc0001c6480, 0xc00099c7e0)
>     k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:90 +0x25
> created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
>     github.com/minio/operator/pkg/controller/cluster/main-controller.go:397 +0x3c5
> Stream closed EOF for minio-operator/minio-operator-6f4f49887d-55pj4 (minio-operator)
> ```

If tenant has no config file we should throw an error and stop execution for that tenant, meaning if theres a version of that tenant already running thats fine,  but we should not apply any new incoming changes, that sounds good?

2022-08-30 21:43 UTC, dvaldivia approved these changes

2022-08-30 22:29 UTC, harshavardhana commented
Are we ready to make v5.0.0 @dvaldivia ?

2022-08-31 05:11 UTC, merged