fix: ParseRawConfiguration bug
minio/operator pull request #1088
Opened 2022-04-07 06:22 UTC by Alevsk

- configuration parse was failing when env value contains multiple `=`

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2022-04-07 06:23 UTC, dvaldivia submitted a review, later dismissed

2022-04-07 06:40 UTC, harshavardhana requested changes
Please add a unit test that covers all possible scenarios. Take a look at server side implementation for a more generic parsing logic for config_env

2022-04-07 21:45 UTC, harshavardhana submitted a review, later dismissed

2022-04-08 00:37 UTC, dvaldivia approved these changes

2022-04-08 00:56 UTC, harshavardhana approved these changes

2022-04-08 01:14 UTC, bexsoft approved these changes

2022-04-08 01:15 UTC, merged