Add AuditLog support to Tenant Helm Chart
minio/operator pull request #1117
Opened 2022-05-11 19:51 UTC by cniackz

2022-05-12 16:33 UTC, dvaldivia approved these changes

2022-05-12 16:53 UTC, Alevsk requested changes

2022-05-12 16:53 UTC, Alevsk commented on helm/tenant/templates/tenant.yaml
> +      runAsNonRoot: true
we allow the user to customize this value too

2022-05-12 16:53 UTC, Alevsk commented on helm/tenant/templates/tenant.yaml
> +        runAsNonRoot: true
we allow the user to customize this value too

2022-05-17 06:23 UTC, Alevsk approved these changes

2022-05-17 06:43 UTC, merged