Add a note about settings requestAutoCert to False explicitly when providing certificates to minio
minio/operator pull request #1184
Opened 2022-06-23 02:21 UTC by artazar

Long story short: instead of setting it to False, I removed the setting, and this led to unexpected and unclear issues with minio serving two different certificates. So I suggest this is made more clear in the docs.

2022-06-24 13:25 UTC, ravindk89 commented
Q: Does this mean we do not support both autoTLS + Custom Certs? I had assumed we did because we have SNI support in the baremetal env.

It feels helpful to have both - I can have a K8s cluster-wide signed cert for internal TLS and an ingress/LB/external cert for everything else.

maybe I am misunderstanding.

2022-06-28 00:13 UTC, artazar commented
Hi @ravindk89 
Well this poses a bit greater discussion then, because the exact reason I am raising this PR is an unexpected behavior of Minio I experienced due to this mistake I made, letting Minio serve both auto-generated and manually added certificates. The misbehavior in this case is that minio-server process responds randomly with one cert or another, adding chaotic errors to the communications within the cluster.
In tech terms, I was continuously curl'ing it on https port (with my custom CA cert), and approximately 1 out of 10 responses was an error, indicating that minio used a different certificate treating this errored request.
So if Minio is to accept multiple certs and use them properly, then its behavior should be rechecked and fixed.
Otherwise I would go with highlighting that only one way of providing certificates is possible at a time, and all alternative names should be included into this single certificate.
Let me know your thoughts and if you think this story should be extended and raised as a separate minio issue and not a docs issue.

2022-06-28 04:58 UTC, harshavardhana requested changes

2022-06-28 04:58 UTC, harshavardhana commented on docs/tls.md
> +Once created, set the name of Secret (here it is `tls-ssl-minio`) under `spec.externalCertSecret` field. Then create the Tenant. MinIO Operator will use this Secret to fetch key and certificate and m
This is not necessary however the wording should be made optional here, I think this document update is not necessary or should be written differently.

2022-06-28 04:58 UTC, harshavardhana commented on docs/tls.md
> +Once created, set the name of Secret (here it is `tls-ssl-minio`) under `spec.externalCertSecret` field. Then create the Tenant. MinIO Operator will use this Secret to fetch key and certificate and m
```suggestion
Once created, set the name of Secret (here it is `tls-ssl-minio`) under `spec.externalCertSecret` field. Then create the Tenant. MinIO Operator will use this Secret to fetch the key and certificate and mount it to relevant locations inside the Tenant pods. 

NOTE: Additionally to disable automatic cert generation make sure the `spec.requestAutoCert` field to `false`.
```

2022-06-28 04:58 UTC, harshavardhana commented on docs/tls.md
> +Make sure you explicitly set `requestAutoCert` field to `false` to disable automatic generation.
```suggestion
Additionally to disable automatic cert generation make sure the `spec.requestAutoCert` field to `false`.
```

2022-06-28 16:23 UTC, Alevsk commented
> Hi @ravindk89 Well this poses a bit greater discussion then, because the exact reason I am raising this PR is an unexpected behavior of Minio I experienced due to this mistake I made, letting Minio serve both auto-generated and manually added certificates. The misbehavior in this case is that minio-server process responds randomly with one cert or another, adding chaotic errors to the communications within the cluster. In tech terms, I was continuously curl'ing it on https port (with my custom CA cert), and approximately 1 out of 10 responses was an error, indicating that minio used a different certificate treating this errored request. So if Minio is to accept multiple certs and use them properly, then its behavior should be rechecked and fixed. Otherwise I would go with highlighting that only one way of providing certificates is possible at a time, and all alternative names should be included into this single certificate. Let me know your thoughts and if you think this story should be extended and raised as a separate minio issue and not a docs issue.

Please share the error that you are using as well as steps you did to replicate the issue (examples of hostnames on the certificates, etc), MinIO serving multiple certificates is intended functionality, depending on the hostname requested by the client during the request MinIO will serve one certificate or another (SNI support), now, if two certificates contains the same hostname it will always return the first one that got loaded into the certificate pool.

If you decide to use only customer provided certificates you have to make sure that certificate contains valid hostnames for MinIO internode communication https://github.com/minio/operator/blob/master/docs/examples.md#minio-tenant-with-tls-via-customer-provided-certificates

2022-06-29 02:15 UTC, artazar commented
Hi @Alevsk
Thank you for looking into this. Since I have already remediated this on the production cluster I am using, I will spend some time trying to replicate this on a sandbox and get back to you!

2022-07-14 02:18 UTC, artazar commented
Hi @Alevsk 

I have managed to reproduce this on a vanilla environment. Basically this is indeed a hostname collision in 2 different certs, but this statement is definitely disproved by my test:
> if two certificates contains the same hostname it will always return the first one that got loaded into the certificate pool

So step by step reproduction:

1/ Bootstrap minio in minikube

```
minikube start minio --cpus 4 --memory 4g
kubectl krew install minio
kubectl minio init
kubectl minio tenant create certs --capacity 50Gi -n minio-operator --servers 1 --volumes 4
```

2/ Wait for the 'initialized' state of the tenant:

```
kubectl minio tenant list    
```
The output should be like:
```
Tenant 'certs', Namespace 'minio-operator', Total capacity 50 GiB

  Current status: Initialized 
  MinIO version: minio/minio:RELEASE.2022-03-22T02-05-10Z 
```

3/ Check the default returned certificate:

add nginx deployment
```
kubectl -n default create deploy nginx --image nginx
```
ping it with openssl:
```
kubectl -n default exec deploy/nginx -- openssl s_client -connect minio.minio-operator.svc.cluster.local:443 2>&1 | head -5
```
see the output:
```
depth=0 O = system:nodes, CN = system:node:*.certs-hl.minio-operator.svc.cluster.local
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 O = system:nodes, CN = system:node:*.certs-hl.minio-operator.svc.cluster.local
verify error:num=21:unable to verify the first certificate
```

4/ now, not sure why, but default root secret is not created automatically, it should be added manually, I got the error from minio-operator:

```
E0714 01:55:53.494066       1 main-controller.go:559] error syncing 'minio-operator/certs': secrets "certs-creds-secret" not found
```
did not stop here, just added it:
```
kubectl create secret generic certs-creds-secret -n minio-operator --from-literal=accesskey=admin --from-literal=secretkey='1027998b-79ad-4f67-9249-528b08231f08'
```

5/ install cert-manager:

```
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.yaml
```
create cluster issuer and a new minio cert (put it all into a public gist to avoid long wall of text) 
```
kubectl apply -f https://gist.githubusercontent.com/artazar/02497b9f4861190f064cca32abe93342/raw/df026d5ef7973dc2b6b7cfbc68d522c7cdf6884d/gistfile1.txt
```

6/ edit the tenant and add the external cert:

```
kubectl edit tenant -n minio-operator certs   
```
add section to spec:
```
  externalCertSecret:
    - name: certs-tls
      type: cert-manager.io/v1
```
now we have both kinds of certs in place:
```
kubectl exec  -n minio-operator certs-ss-0-0 -- ls -al /tmp/certs        
```
we get both hostname-1 dir and public.crt in the output:
```                      
total 4
drwxrwsrwt 3 root 1000  160 Jul 14 01:57 .
drwxrwxrwt 1 root root 4096 Jul 14 01:57 ..
drwxr-sr-x 4 root 1000  120 Jul 14 01:57 ..2022_07_14_01_57_56.3114090969
lrwxrwxrwx 1 root 1000   32 Jul 14 01:57 ..data -> ..2022_07_14_01_57_56.3114090969
lrwxrwxrwx 1 root 1000   10 Jul 14 01:57 CAs -> ..data/CAs
lrwxrwxrwx 1 root 1000   17 Jul 14 01:57 hostname-1 -> ..data/hostname-1
lrwxrwxrwx 1 root 1000   18 Jul 14 01:57 private.key -> ..data/private.key
lrwxrwxrwx 1 root 1000   17 Jul 14 01:57 public.crt -> ..data/public.crt
```

7/ finally confirm that the returned certificate may get changed on subsequent requests, just run the command multiple times:

```
# kubectl -n default exec deploy/nginx -- openssl s_client -connect minio.minio-operator.svc.cluster.local:443 2>&1 | head -5
```
and see either one:
```
depth=0 CN = s3.example.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = s3.example.com
verify error:num=21:unable to verify the first certificate
```
or the other:
```
depth=0 O = system:nodes, CN = system:node:*.certs-hl.minio-operator.svc.cluster.local
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 O = system:nodes, CN = system:node:*.certs-hl.minio-operator.svc.cluster.local
verify error:num=21:unable to verify the first certificate
```

2022-08-31 05:12 UTC, harshavardhana commented
this is not needed anymore #1259

2022-08-31 05:12 UTC, closed without merging