Add Status sub command and small refactor
minio/operator pull request #1196
Opened 2022-07-05 22:40 UTC by reivaj05

Closes: https://github.com/miniohq/engineering/issues/703

2022-07-05 23:47 UTC, harshavardhana requested changes

2022-07-05 23:47 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-status.go
> +	fmt.Printf(Blue("Capacity: %.1fGi \n", float32(tenant.Status.Usage.Capacity)/gb))
you can use `humanize.IBytes(tenant.Status.Usage.Capacity)`  = there is no reason to manually perform division.

2022-07-05 23:47 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-status.go
> +	fmt.Printf(Blue("Capacity: %.1fGi \n", float32(tenant.Status.Usage.Capacity)/gb))
```suggestion
	fmt.Printf(Blue("Usable Capacity: %.1fGi \n", float32(tenant.Status.Usage.Capacity)/gb))
```

2022-07-05 23:47 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-status.go
> +	fmt.Printf(Blue("Raw usage: %.1fGi \n", float32(tenant.Status.Usage.RawUsage)/gb))
```suggestion
```

We do not need to show this - we should perhaps keep a terse output instead of wide output.

2022-07-05 23:47 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-status.go
> +	fmt.Printf(Green(fmt.Sprintf("JSON:\n\n%s\n\n", string(statusJSON))))
```suggestion
	fmt.Printf(Green(fmt.Sprintf("JSON:\n\n%s\n\n", string(statusJSON))))
```

I think we can avoid adding `JSON:` this is not parsable by `jq` - instead we can simply have the actual json output just 

```
enc := json.NewEncoder(d.out)
enc.SetIndent("", " ")

if err := enc.Encode(tenant.Status); err != nil {
}
```

2022-07-05 23:47 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-status.go
> +	fmt.Printf(Yellow("YAML:\n\n%s", string(statusYAML)))
```suggestion
        fmt.Fprintln(d.out, string(statusYAML))
```

2022-07-05 23:47 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-status.go
> +	fmt.Printf(Blue("Capacity: %.1fGi \n", float32(tenant.Status.Usage.Capacity)/gb))
construct this entire string in `strings.Builder` object

```
var s strings.Builder

s.WriteString(Blue("Current status: %s \n", tenant.Status.CurrentState))
...
```

at the end then do this

```
fmt.Fprintln(d.out, s.String())
```

2022-07-06 23:54 UTC, cniackz approved these changes
LGTM

2022-07-06 23:54 UTC, merged