To delete audit log config when disabled
minio/operator pull request #1208
Opened 2022-07-18 19:02 UTC by cniackz

2022-07-18 19:15 UTC, harshavardhana requested changes

2022-07-18 21:55 UTC, cniackz commented
Thank you @harshavardhana for the review. I have addressed the changes. Once all tests pass again, please review it again.

2022-07-18 22:04 UTC, reivaj05 approved these changes

2022-07-19 01:52 UTC, harshavardhana approved these changes

2022-07-19 01:52 UTC, merged