kubectl-minio command to register tenants in SUBNET
minio/operator pull request #1258
Opened 2022-08-25 18:52 UTC by reivaj05

Adds new kubectl-minio to register tenants in SUBNET

kubectl minio license register (It will ask for SUBNET credentials to retrieve API KEY)
kubectl minio license register --api-key {API_KEY}

Closes: https://github.com/miniohq/engineering/issues/917

2022-08-30 17:36 UTC, dvaldivia submitted a review, later dismissed

2022-08-30 20:37 UTC, Alevsk submitted a review, later dismissed
Please address the following code issues

```
Running lint check
Building 'kubectl-minio' binary
?       github.com/minio/kubectl-minio  [no test files]
?       github.com/minio/kubectl-minio/cmd      [no test files]
?       github.com/minio/kubectl-minio/cmd/helpers      [no test files]
?       github.com/minio/kubectl-minio/cmd/resources    [no test files]
cmd/helpers/helpers.go:253:1: exported: comment on exported function AskNumber should be of the form "AskNumber ..." (revive)
// Ask user for number input."
^
cmd/helpers/helpers.go:296:1: exported: exported function GetTenantConfiguration should have comment or be unexported (revive)
func GetTenantConfiguration(ctx context.Context, tenant *miniov2.Tenant, clientSet *kubernetes.Clientset) (map[string][]byte, error) {
^
cmd/helpers/helpers.go:264:11: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)
                        } else {
                                return nil
                        }
cmd/helpers/helpers.go:284:11: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)
                        } else {
                                return nil
                        }
make: *** [Makefile:76: plugin] Error 1
```

you can run the `make` command in the operator folder to check theres no more issues once the above issues are fixed, Im adding a test to run this check automatically

2022-09-01 21:11 UTC, pjuarezd requested changes

2022-09-01 23:34 UTC, reivaj05 commented on kubectl-minio/cmd/license-register.go
> +			return err
Should be fine  to just continue to the next tenant on error for now

2022-09-01 23:35 UTC, reivaj05 commented on kubectl-minio/cmd/license-register.go
> +	adminClient, err := d.getTenantAdminClient(ctx, tenant, kubeClient)
Your minio service is not reachable locally, I use [kubefwd](https://kubefwd.com/) to expose services locally

2023-03-07 01:35 UTC, cniackz commented
@reivaj05 please resolve the conflicts 👍

2023-08-12 02:58 UTC, closed without merging