fix poolSSMatchesSpec function
minio/operator pull request #1259
Opened 2022-08-27 01:52 UTC by Alevsk

- simplify poolSSMatchesSpec function
- detect changes on objectMeta and spec
- fix tenant won't restart after certificates are added/removed or
  autocert is enabled
- fix user can upload ca certificate without enabling autocert

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2022-08-29 17:33 UTC, harshavardhana requested changes
Please run `go mod tidy -compat=1.17` locally @Alevsk

2022-08-29 17:56 UTC, Alevsk commented
> Please run `go mod tidy -compat=1.17` locally @Alevsk

done @harshavardhana

2022-08-29 20:31 UTC, harshavardhana approved these changes

2022-08-30 08:59 UTC, Praveenrajmani approved these changes

2022-08-30 15:27 UTC, merged