Include vulncheck in make
minio/operator pull request #1285
Opened 2022-09-13 17:25 UTC by pjuarezd

2022-09-13 23:13 UTC, pjuarezd commented
Vulncheck is failing in 1.18 due to a problem with report GO-2022-0969, it's supposed to be fixed in 1.1.8.6 however the utility stills markes it as vulnerable, reported on https://github.com/golang/vulndb/issues/996

2022-09-14 04:26 UTC, harshavardhana requested changes

2022-09-14 04:26 UTC, harshavardhana commented on .github/workflows/vulncheck.yml
> +        go-version: [ 1.18, 1.19 ]
you shouldn't run `vulncheck` for 1.18 change it to just use 1.19.x @pjuarezd

2022-09-14 05:37 UTC, harshavardhana approved these changes

2022-09-14 05:37 UTC, merged