Release v4.5.1
minio/operator pull request #1295
Opened 2022-09-20 21:55 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-09-20 21:58 UTC, harshavardhana requested changes
We shouldn't make a release until this is fixed https://github.com/minio/operator/issues/1294

2022-09-21 18:01 UTC, bexsoft approved these changes

2022-09-21 18:02 UTC, harshavardhana approved these changes

2022-09-21 18:02 UTC, Alevsk approved these changes

2022-09-21 18:02 UTC, merged