Add containersecuritycontext helm
minio/operator pull request #1372
Opened 2022-12-16 11:31 UTC by allanrogerr

Modified tenant CRD to support CSC under pools
Modified tenant statefulset to support CSC
Added support for CSC on Helm chart
Added implementation examples to 
- examples/kustomization/base/tenant.yaml
- examples/kustomization/tenant-lite/tenant.yaml
Avoided operator upgrade tests where example yamls do not correspond to the operator binary. In this case, the test chooses a lower version as being the current branch of the operator

Todo
Make sure that if the kubernetes version doesn't support CSC to stop the sync of the tenant with an error (tenant.Validate()) in theory <1.22

2022-12-17 01:17 UTC, dvaldivia approved these changes
I tested all the way down to k8s `v1.19` and it seems to be working fine.

2022-12-19 15:46 UTC, cniackz commented
Tested locally, couple of comments:

1. We already put the securityContext of a container prior this change, tested but we couldn't modify it.
2. With this change, we can now modify it, which is good and tested.
3. But I still see missing fields like `fsGroupChangePolicy` that if set not to always it can shorten the time to deploy our pod.

Please read at:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

Specifically at:
```
OnRootMismatch: Only change permissions and ownership if the permission and the ownership of root directory does not match with expected permissions of the volume. This could help shorten the time it takes to change ownership and permission of a volume.
```

So I suggest to apply any missing field on `securityContext` to provide more configuration options, all possible is the ideal.

2022-12-19 15:47 UTC, cniackz requested changes
Please add missing fields on `securityContext` like: `fsGroupChangePolicy`

2022-12-19 15:47 UTC, cniackz commented
But overall good Job Allan, you impressed me on how fast you got this change to properly work in k8s 👍

2022-12-19 15:59 UTC, dvaldivia commented
there's no `fsGroupChangePolicy` for Container SecurityContext it seems

2022-12-19 16:49 UTC, allanrogerr commented
> Tested locally, couple of comments:
> 
> 1. We already put the securityContext of a container prior this change, tested but we couldn't modify it.
> 2. With this change, we can now modify it, which is good and tested.
> 3. But I still see missing fields like `fsGroupChangePolicy` that if set not to always it can shorten the time to deploy our pod.
> 
> Please read at: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
> 
> Specifically at:
> 
> ```
> OnRootMismatch: Only change permissions and ownership if the permission and the ownership of root directory does not match with expected permissions of the volume. This could help shorten the time it takes to change ownership and permission of a volume.
> ```
> 
> So I suggest to apply any missing field on `securityContext` to provide more configuration options, all possible is the ideal.

Thanks @dvaldivia - @cniackz When reviewing ContainerSecurityContext (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#securitycontext-v1-core), I noted that the available fields do not include several from PodSecurityContext (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#podsecuritycontext-v1-core).

2022-12-19 16:57 UTC, allanrogerr commented
> I tested all the way down to k8s `v1.19` and it seems to be working fine.

@dvaldivia Do we still need the floor test then? It may be useful in the future. Let me know.

2022-12-19 17:04 UTC, dvaldivia commented
yes, we merged https://github.com/minio/operator/pull/1304 but we set the floor to `v1.21` of k8s @allanrogerr

2022-12-19 17:43 UTC, cniackz approved these changes
LGTM

2022-12-19 19:26 UTC, dilverse submitted a review, later dismissed
Awesome stuff @allanrogerr! 🤘

2022-12-19 21:52 UTC, allanrogerr commented
fixes: https://github.com/minio/operator/issues/1366

2022-12-19 23:25 UTC, allanrogerr commented
fixes: https://github.com/minio/operator/issues/1310

2022-12-19 23:26 UTC, allanrogerr commented
fixes: https://github.com/minio/operator/issues/1267

2022-12-20 16:49 UTC, allanrogerr commented
@dvaldivia @cniackz I have added the defaulting capability as requested
https://github.com/minio/operator/pull/1372/commits/0bd5ab79c2e9834771286512207d02cda1925729

2022-12-20 17:46 UTC, allanrogerr commented
Tests
1.- Pull allanrogerr:add-containersecuritycontext-helm
2.- After commenting out "destroy_kind", run ./testing/check-helm.sh 
3.- Observe operator and console without Container Security Context
4.- After commenting out "destroy_kind", run ./testing/deploy-tenant.sh 
5.- Observe operator and console without Container Security Context

6.- Modify temporarily
	helm/operator/values.yaml
		Add the following yaml snippet under "console" and "operator"
	helm/tenant/values.yaml
		Add the following yaml snippet under "pools"

		containerSecurityContext:
	    runAsUser: 1000
	    runAsGroup: 1000
	    runAsNonRoot: true
	    allowPrivilegeEscalation: false
	    readOnlyRootFilesystem: false
	    capabilities:
	      add:
	        - ALL
	      drop:
	        - ALL

	examples/kustomization/tenant-lite/tenant.yaml
		Add the following yaml snippet under "pools"

		containerSecurityContext:
	    runAsUser: 1000
	    runAsGroup: 1000
	    runAsNonRoot: true
	    allowPrivilegeEscalation: false
	    readOnlyRootFilesystem: false
	    capabilities:
	      add:
	        - ALL
	      drop:
	        - ALL

	resources/base/console-ui.yaml
	resources/base/deployment.yaml
		Add the following yaml snippet under "containers"

		securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        add:
          - ALL
        drop:
          - ALL

7.- Run ./testing/check-helm.sh again
8.- After the test completes, observe operator, console and tenant output yamls with the above Container Security Context
	e.g.
		k get pod/minio1-pool-0-0 -n default -o yaml
		k get pod/console-68766cb74-x5hwn -n minio-operator -o yaml
		k get pod/minio-operator-8bbdb59d6-94j4m -n minio-operator -o yaml

9.- Run ./testing/deploy-tenant.sh again
10.- After the test completes, observe operator, console and tenant output yamls with the above Container Security Contexts
	e.g.
		 k get pod/storage-lite-pool-0-0 -n tenant-lite -o yaml
		 k get pod/console-7f7699948f-hjrq7 -n minio-operator -o yaml
		 k get pod/minio-operator-95c4dc86-zs5s9 -n minio-operator -o yaml

2022-12-20 17:49 UTC, dvaldivia submitted a review, later dismissed

2022-12-21 14:21 UTC, cniackz commented
Read comments, and review the code changes, and it looks good to me.
Last time I tested this PR with Kustomize, this time I will test is with Helm and if all goes well, then I will approve and notify Allan about it.

2022-12-21 15:33 UTC, cniackz commented on helm/tenant/values.yaml
> +      securityContext:
`securityContext` is already defined above as empty braces:

```yaml
      ## Configure security context
      securityContext: { }
```

Shouldn't we keep only one copy of this value?

2022-12-21 15:34 UTC, cniackz reviewed
Allan, minor comment for `helm/tenant/values.yaml`, please take a look and keep one copy of `securityContext` in the values.

2022-12-21 17:03 UTC, dilverse approved these changes

2022-12-21 17:23 UTC, cniackz commented
Thank you for the fix Allan :)

2022-12-21 17:24 UTC, cniackz approved these changes
LGTM

2022-12-21 17:27 UTC, pjuarezd approved these changes

2022-12-21 18:21 UTC, merged