small release scripts fixes
minio/operator pull request #1382
Opened 2023-01-04 03:43 UTC by pjuarezd

* yq is receiving more than one yaml document, in some yq versions it could lead to not catch the version when releasing RedHat OLM

* helm-reindex was being invoked twice, removing one

2023-01-04 04:24 UTC, harshavardhana approved these changes

2023-01-09 19:16 UTC, dvaldivia requested changes

2023-01-09 19:16 UTC, dvaldivia commented on Makefile
> -	@./helm-reindex.sh
I think we should still do this on the release target

2023-01-09 19:19 UTC, dvaldivia approved these changes

2023-01-09 19:19 UTC, merged