Release v4.5.7
minio/operator pull request #1392
Opened 2023-01-12 08:08 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2023-01-12 15:02 UTC, allanrogerr submitted a review, later dismissed
I notice you're pointing to ```image: minio/operator:v4.5.7``` now instead of [quay.io](http://quay.io/). Is this on purpose?

2023-01-12 17:01 UTC, reivaj05 approved these changes

2023-01-12 17:49 UTC, pjuarezd requested changes

2023-01-12 17:49 UTC, pjuarezd commented on bundles/certified-operators/4.5.7/manifests/dup1_console-sa-secret_v1_secret.yaml
> +apiVersion: v1
duplicated file, can be deleted

2023-01-12 17:49 UTC, pjuarezd commented on bundles/certified-operators/4.5.7/manifests/dup2_console-env_v1_configmap.yaml
> +apiVersion: v1
duplicated file, can be deleted

2023-01-12 17:49 UTC, pjuarezd commented on bundles/certified-operators/4.5.7/manifests/minio-operator.clusterserviceversion.yaml
> +                - watch
starting on line 79 up to this one can be removed, the Grants are being duplicated

2023-01-12 17:49 UTC, pjuarezd commented on bundles/certified-operators/4.5.7/manifests/minio-operator.clusterserviceversion.yaml
> +        - label:
this service can be removed, is a duplicated of console

2023-01-12 17:49 UTC, pjuarezd commented on bundles/certified-operators/4.5.7/manifests/minio-operator.clusterserviceversion.yaml
> +                    image: minio/operator:v4.5.7
image should be quay.io/minio/operator:v4.5.7

2023-01-12 17:49 UTC, pjuarezd commented on bundles/community-operators/4.5.7/manifests/dup0_console_v1_service.yaml
> +apiVersion: v1
this file is a duplicate can be removed

2023-01-12 17:49 UTC, pjuarezd commented on bundles/community-operators/4.5.7/manifests/dup1_console-sa-secret_v1_secret.yaml
> +apiVersion: v1
this file is a duplicate, can be removed

2023-01-12 17:49 UTC, pjuarezd commented on bundles/community-operators/4.5.7/manifests/dup2_console-env_v1_configmap.yaml
> +apiVersion: v1
this file is a duplicate, can be removed

2023-01-12 17:49 UTC, pjuarezd commented on bundles/redhat-marketplace/4.5.7/manifests/dup0_console_v1_service.yaml
> +apiVersion: v1
this file is a duplicated, can be removed

2023-01-12 17:49 UTC, pjuarezd commented on bundles/redhat-marketplace/4.5.7/manifests/dup1_console-sa-secret_v1_secret.yaml
> +apiVersion: v1
this file is a duplicated, can be removed

2023-01-12 17:49 UTC, pjuarezd commented on bundles/redhat-marketplace/4.5.7/manifests/dup2_console-env_v1_configmap.yaml
> +apiVersion: v1
this file is a duplicated, can be removed

2023-01-12 17:49 UTC, pjuarezd commented on bundles/redhat-marketplace/4.5.7/manifests/minio-operator-rhmp.clusterserviceversion.yaml-e
> +apiVersion: operators.coreos.com/v1alpha1
-e file should not have made into release, this can be removed

2023-01-12 17:49 UTC, pjuarezd commented on certified-operators/manifests/manifests/minio-operator.clusterserviceversion.yaml
> +                    imagePullPolicy: IfNotPresent
from here to line 756 is a duplication, should be removed

2023-01-12 17:49 UTC, pjuarezd commented on certified-operators/manifests/manifests/minio-operator.clusterserviceversion.yaml
> +                      runAsGroup: 1000
this would break openshift deployments, should be removed

2023-01-12 17:49 UTC, pjuarezd commented on certified-operators/manifests/manifests/minio-operator.clusterserviceversion.yaml
> +                      runAsUser: 1000
this should break openshift deployment, should be removed

2023-01-13 00:17 UTC, pjuarezd commented
It's going to be easier to open a new release PR than fix the conflicts

2023-01-13 00:40 UTC, dvaldivia commented
@pjuarezd problems solved :D please review

2023-01-13 00:55 UTC, pjuarezd submitted a review, later dismissed

2023-01-13 00:56 UTC, pjuarezd reviewed
why are /manifest/* files being duplicated again? there is some files untracked in your local causing this @dvaldivia I cannot reproduce it

2023-01-13 05:50 UTC, harshavardhana commented
Can we have one release PR ? Looks like duplicate of #1396

2023-01-13 05:53 UTC, closed without merging

2023-01-13 05:54 UTC, pjuarezd commented
sure, forgot to close this one @harshavardhana