Increase threshold
minio/operator pull request #1499
Opened 2023-03-11 19:20 UTC by reivaj05

2023-03-11 19:21 UTC, harshavardhana requested changes
increase threshold of?

2023-03-11 19:27 UTC, reivaj05 commented
@harshavardhana unit test coverage of operator dashboard, current coverage is 63.3%

2023-03-12 00:57 UTC, harshavardhana approved these changes

2023-03-13 04:55 UTC, dvaldivia approved these changes

2023-03-13 08:56 UTC, merged