Add support for GCP fleet workload identity in KES
minio/operator pull request #1501
Opened 2023-03-14 11:14 UTC by Praveenrajmani

This allows KES to use the workload identity to communicate with GCP secret store instead of managing and rotating the GCP service account.

This PR provides the support by mounting the default app credentials to the KES pods via k8s secret.

For more details, please refer https://cloud.google.com/anthos/fleet-management/docs/use-workload-identity.

Steps to test 

- Pre-requisites: Enable workload identity, register your cluster to the fleet and provide necessary iam permissions of the kuberenetes service account that is going to be used. The guidelines are provided in https://cloud.google.com/anthos/fleet-management/docs/use-workload-identity (NOTE: For DEV testing, please ping me in private and i will share the creds)
- Replace the placeholders `<WORKLOAD_IDENTITY_POOL>`, `<IDENTITY_PROVIDER>`, `<GSA_NAME>`, `<GSA_PROJECT_ID>`, `<PROJECT_ID>`,`<SERVICE_ACCOUNT>`,`<WORKLOAD_IDENTITY_POOL>` with appropriate values from you GCP console. To know how to extract these values, please refer https://cloud.google.com/anthos/fleet-management/docs/use-workload-identity#impersonate_a_service_account
- Apply the manifests
```
kustomize build examples/kustomization/tenant-kes-encryption-gcp | kubectl apply -f -
```
- The tenant should be up and a new key specified in `keyName` in the KES config should be created

2023-03-21 05:28 UTC, pjuarezd requested changes

2023-03-21 05:28 UTC, pjuarezd commented on examples/kustomization/tenant-kes-encryption/tenant.yaml
> +    image: "" # minio/kes:v0.22.3
Latest KES version https://github.com/minio/kes/releases/tag/2023-02-15T14-54-37Z
```suggestion
    image: "" # minio/kes:2023-02-15T14-54-37Z
```

2023-03-21 05:28 UTC, pjuarezd commented on kubectl-minio/cmd/helpers/constants.go
> +	DefaultKESImage = "minio/kes:v0.22.3"
Latest KES version https://github.com/minio/kes/releases/tag/2023-02-15T14-54-37Z

```suggestion
	DefaultKESImage = "minio/kes:2023-02-15T14-54-37Z"
```

2023-03-21 05:28 UTC, pjuarezd commented on logsearchapi-bin
Please remove this binary, logsearch will be deprecated on operator v5

2023-03-21 05:28 UTC, pjuarezd commented on pkg/apis/minio.min.io/v2/constants.go
> +const DefaultKESImage = "minio/kes:v0.22.3"
```suggestion
const DefaultKESImage = "minio/kes:2023-02-15T14-54-37Z"
```

2023-03-21 17:49 UTC, pjuarezd approved these changes

2023-03-26 23:19 UTC, dvaldivia approved these changes

2023-03-26 23:30 UTC, pjuarezd approved these changes

2023-03-26 23:30 UTC, merged