Fixing issue due to missing tenant being removed
minio/operator pull request #1546
Opened 2023-04-03 17:49 UTC by cniackz

2023-04-03 17:56 UTC, harshavardhana requested changes

2023-04-03 17:56 UTC, harshavardhana commented on pkg/controller/main-controller.go
> +		if temporaltenant, err := c.updateCustomCertificatesStatus(ctx, tenant, customCertificates); err != nil {
```suggestion
		if newTenant, err := c.updateCustomCertificatesStatus(ctx, tenant, customCertificates); err != nil {
```

2023-04-03 17:56 UTC, harshavardhana commented on pkg/controller/main-controller.go
> +			tenant = temporaltenant
```suggestion
			tenant = newTenant
```

2023-04-03 18:19 UTC, allanrogerr approved these changes

2023-04-03 18:45 UTC, reivaj05 approved these changes

2023-04-04 04:47 UTC, Praveenrajmani approved these changes

2023-04-05 12:52 UTC, merged