Update manifests for release 5.0.6
minio/operator pull request #1668
Opened 2023-06-28 18:54 UTC by pjuarezd

Operator deployment got update to include deployment strategy `Recreate` in the operator deployment, this will force to delete old deployment pods before create the new deployment, (se more in [Kubernetes docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment) about this strategy)

This should address the Isuue on Openshift deployments, where operator updates fails because the installPlan fails, and the installPlan fails because it cannot schedule  more than one Operator pod in a node.

We don't want to remove the spread strategy, but we can be more aggressive on the rollout strategy by killing old deploy pods.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
spec:
  replicas: 2
  selector:
    matchLabels:
      name: minio-operator
  strategy:
    type: Recreate
...
```

2023-06-28 19:50 UTC, harshavardhana approved these changes

2023-06-29 01:25 UTC, jiuker requested changes

2023-06-29 01:25 UTC, jiuker commented on bundles/certified-operators/5.0.6/manifests/minio-operator.clusterserviceversion.yaml
> -                      runAsNonRoot: true
Is the deletion of this here on purpose? I'm not sure.

2023-06-30 00:15 UTC, jiuker approved these changes

2023-06-30 07:50 UTC, merged