Add --force flag to minio  delete command
minio/operator pull request #1687
Opened 2023-07-15 05:06 UTC by r-scheele

This pr is based on the issue [here](https://github.com/minio/operator/issues/1683)

2023-07-15 09:10 UTC, harshavardhana requested changes

2023-07-15 09:10 UTC, harshavardhana commented on kubectl-minio/cmd/delete.go
> +	f.BoolVarP(&o.force, "force", "f", false, "force delete without confirmation")
```suggestion
	f.BoolVarP(&o.force, "force", "f", false, "allow deleting without confirmation")
```

2023-07-15 09:10 UTC, harshavardhana commented on kubectl-minio/cmd/delete.go
> +	f.BoolVarP(&o.force, "force", "f", false, "force delete without confirmation")
We should also add another flag `--dangerous` since this is not a "reversible" operation

2023-07-15 09:10 UTC, harshavardhana commented on kubectl-minio/cmd/delete.go
> -			if !helpers.Ask("Are you sure you want to delete ALL the MinIO Tenants and MinIO Operator, this is not a reversible operation") {
```suggestion
if !helpers.Ask("Are you sure you want to delete ALL the MinIO Tenants and MinIO Operator, this is irreversible") {
```

2023-07-19 12:44 UTC, cniackz commented
@r-scheele please address the last change requested by @harshavardhana and make sure to test this truly and if possible post the testing results on your PR.

Thank you very much! 👍

2023-07-19 13:22 UTC, r-scheele commented
> @r-scheele please address the last change requested by @harshavardhana and make sure to test this truly and if possible post the testing results on your PR.
> 
> Thank you very much! 👍

Hi @cniackz, can you check the pr description now?

2023-07-25 19:03 UTC, pjuarezd approved these changes

2023-07-25 19:04 UTC, harshavardhana approved these changes

2023-07-25 19:10 UTC, merged

2023-07-25 22:52 UTC, pjuarezd commented
Closes https://github.com/minio/operator/issues/1683