feat:add runtime to easy use for createOrCreate
minio/operator pull request #1715
Opened 2023-08-08 10:38 UTC by jiuker

feat:add runtime to easy use for createOrCreate

2023-08-09 02:17 UTC, pjuarezd commented
needs  a little `go mod tidy`

2023-08-10 19:17 UTC, harshavardhana requested changes

2023-08-10 19:17 UTC, harshavardhana commented on pkg/runtime/tools.go
> +package runtime
Please add the missing license header, borrow from other files.

2023-08-10 19:17 UTC, harshavardhana commented on pkg/runtime/sync.go
> +package runtime
license header misssing.

2023-08-22 03:15 UTC, pjuarezd approved these changes

2023-08-22 03:28 UTC, pjuarezd approved these changes

2023-08-29 01:48 UTC, jiuker commented
@harshavardhana @shtripat  PTAL

2023-08-29 02:45 UTC, harshavardhana approved these changes

2023-08-29 02:45 UTC, merged