fix:update dep to fix #1610
minio/operator pull request #1730
Opened 2023-08-17 03:15 UTC by jiuker

update dep to fix #1610
https://github.com/minio/operator/issues/1610
update the validate version for https://github.com/go-openapi/validate/pull/152 merged

2023-08-17 10:27 UTC, shtripat submitted a review, later dismissed
lgtm

2023-08-19 03:22 UTC, harshavardhana requested changes

2023-08-19 03:22 UTC, harshavardhana commented on .github/workflows/ui.yaml
> +          pwd
what is this for?

2023-08-19 03:22 UTC, harshavardhana commented on .github/workflows/ui.yaml
> +          find / -name *.out
what is this for?

2023-08-19 03:23 UTC, jiuker commented on .github/workflows/ui.yaml
> +          find / -name *.out
I am find out why the workflow failed.

2023-08-19 16:03 UTC, pjuarezd approved these changes

2023-08-20 13:16 UTC, harshavardhana approved these changes

2023-08-20 13:17 UTC, merged