disable anonymous logging in tenant helm chart
minio/operator pull request #1776
Opened 2023-09-14 04:55 UTC by kanagarajkm

2023-09-14 04:56 UTC, harshavardhana requested changes

2023-09-14 04:56 UTC, harshavardhana commented on helm/tenant/values.yaml
>      quiet: true
Even this can go

2023-09-14 04:56 UTC, harshavardhana commented on helm/tenant/values.yaml
>      quiet: true
Simply remove it.

2023-09-14 05:36 UTC, kanagarajkm commented on helm/tenant/values.yaml
>      quiet: true
@harshavardhana done

2023-09-14 06:23 UTC, harshavardhana requested changes
actually we can get rid of all of them

2023-09-14 06:23 UTC, harshavardhana commented on helm/tenant/values.yaml
>      quiet: true
```suggestion
```

2023-09-14 06:23 UTC, harshavardhana commented on helm/tenant/values.yaml
>      json: true
```suggestion
```

2023-09-14 07:06 UTC, kanagarajkm commented on helm/tenant/values.yaml
>      quiet: true
done

2023-09-14 07:06 UTC, kanagarajkm commented on helm/tenant/values.yaml
>      json: true
done

2023-10-16 05:48 UTC, harshavardhana approved these changes

2023-10-16 05:48 UTC, merged