Enable Encryption when the KMS Secret is given as a File
minio/operator pull request #1789
Opened 2023-09-25 21:41 UTC by pschichtel

this has been split out of #1786

2023-09-26 15:21 UTC, jiuker requested changes

2023-09-26 15:33 UTC, pschichtel commented on api/tenant-get-handlers.go
> +	hasKmsSecret := tenantConfiguration["MINIO_KMS_SECRET_KEY"] != "" || tenantConfiguration["MINIO_KMS_SECRET_KEY_FILE"] != ""
minio accepts (I think) all secret env vars both directly and as files. The _FILE variant contains a path to a file in the container, that contains the actual value.

2023-09-26 15:36 UTC, pschichtel commented on api/tenant-get-handlers.go
> +	hasKmsSecret := tenantConfiguration["MINIO_KMS_SECRET_KEY"] != "" || tenantConfiguration["MINIO_KMS_SECRET_KEY_FILE"] != ""
https://github.com/minio/minio/blob/22ee67813618351ca8a983eee65f6460af7d9afe/cmd/common-main.go#L555

2023-09-28 02:42 UTC, jiuker approved these changes

2023-10-16 05:47 UTC, harshavardhana approved these changes

2023-10-16 05:47 UTC, merged