Correcting the name of the Operator Console TLS Secret
minio/operator pull request #1802
Opened 2023-10-07 04:27 UTC by cniackz

2023-10-07 04:37 UTC, pjuarezd approved these changes

2023-10-09 04:32 UTC, shtripat approved these changes
lgtm

2023-10-16 05:46 UTC, harshavardhana requested changes

2023-10-16 05:46 UTC, harshavardhana commented on resources/base/console-ui.yaml
> +                  name: console-tls
is this a breaking change? how does it work now?

2023-11-14 05:46 UTC, pjuarezd requested changes
Actually, I introduced the name of the secreted by default as `console-tls` in kubectl-minio on PR https://github.com/minio/operator/pull/1348

https://github.com/minio/operator/blob/53deac59bc765da572e412f5614f364204a805f4/kubectl-minio/cmd/init.go#L83

And wrongly set the constant to `operator-console-tls` on the same PR
https://github.com/minio/operator/pull/1348/files#diff-0ee76ed6676e7fcf9179ac75e1d5eeb7a6e25b7bc489bb8dec243fd80e247574R40.


I fixed that discrepancy and set the expected secret name as `console-tls` in the PR https://github.com/minio/operator/pull/1712/files

Which test is failing? we should fix the broken test instead

2023-11-14 21:46 UTC, cniackz commented
Ok, if no longer an issue, then we should simply close it.

2023-11-14 21:46 UTC, closed without merging