Parse tenant config properly
minio/operator pull request #1833
Opened 2023-10-26 09:35 UTC by sathieu

avoid parsing error on comments without equal sign

Copied from https://github.com/minio/minio/blob/96ec8fcba1570d0c60efa77615a184b80960be64/cmd/common-main.go#L475C1-L509C2

2023-10-26 09:43 UTC, jiuker commented
Doesn't it seem to cause the environment variables to be read incorrectly? @sathieu

2023-10-26 09:43 UTC, jiuker requested changes
Doesn't it seem to cause the environment variables to be read incorrectly? @sathieu

2023-10-26 09:55 UTC, sathieu commented
> Doesn't it seem to cause the environment variables to be read incorrectly? @sathieu

No. The behavior is exactly the same as MinIO itself.

See  https://github.com/minio/minio/blob/96ec8fcba1570d0c60efa77615a184b80960be64/cmd/common-main.go#L475C1-L509C2

2023-10-26 10:05 UTC, jiuker approved these changes

2023-11-09 04:21 UTC, pjuarezd approved these changes

2023-11-09 04:21 UTC, merged