Add new CRD for minio jobs
minio/operator pull request #1862
Opened 2023-11-16 12:16 UTC by cniackz

2023-11-17 18:08 UTC, dvaldivia requested changes

2023-11-17 18:08 UTC, dvaldivia commented on pkg/apis/miniojobs.min.io/register.go
> +	GroupName = "miniojobs.min.io"
We can use the same GroupName as `Tenant` `minio.min.io` since this will be MinIO specific

2023-11-17 18:08 UTC, dvaldivia commented on pkg/apis/miniojobs.min.io/register.go
> +// Copyright (C) 2022, MinIO, Inc.
wrong year

2023-11-17 18:09 UTC, dvaldivia commented on pkg/controller/controller.go
> +		minioInformerFactory.MinIOJobs().V1alpha1().MinIOJobs(),
let's have the MinIO Job use a separate controller

2024-01-19 20:17 UTC, cniackz commented
Changes will be done in https://github.com/minio/operator/pull/1883

2024-01-19 20:17 UTC, closed without merging