fix : fix incorrect indentation in secrets.existingSecret
minio/operator pull request #1910
Opened 2023-12-15 03:59 UTC by LemonDouble

fix #1909

2023-12-15 16:58 UTC, harshavardhana approved these changes

2023-12-15 17:01 UTC, shtripat submitted a review, later dismissed

2023-12-18 03:11 UTC, jiuker requested changes
Fix the pipeline. plz

2023-12-18 03:54 UTC, LemonDouble commented
@jiuker 

OK. I fixed the pipeline by referring to #1663.

2023-12-18 04:08 UTC, shtripat approved these changes

2023-12-18 08:54 UTC, jiuker commented
What's the different?  @LemonDouble

2023-12-19 16:12 UTC, merged