fix: env MINIO_KMS_KES_CA_PATH into MINIO_KMS_KES_CAPATH
minio/operator pull request #1956
Opened 2024-01-26 09:22 UTC by jiuker

see 
https://github.com/minio/minio/blob/e377bb949a804c934607fa663a2bef40e3806fb8/internal/kms/config.go#L31 
fix https://github.com/minio/operator/issues/1954

2024-01-26 09:29 UTC, harshavardhana requested changes

2024-01-26 09:29 UTC, harshavardhana commented on pkg/resources/statefulsets/minio-statefulset.go
> +			Name:  "MINIO_KMS_KES_CAPATH",
Please keep both @jiuker

2024-01-26 17:24 UTC, shtripat approved these changes

2024-02-10 22:08 UTC, harshavardhana approved these changes

2024-02-10 22:08 UTC, merged