Issue 1984
minio/operator pull request #2026
Opened 2024-03-10 14:41 UTC by JoelRuizRojas

Changes added:

1) Ingress specification added for minio operator console to route http/https traffic to console service 
2) Only support 1 CA certificate for https routing (instead of multiple TLS configurations) since only 1 console service is defined in the ingress configuration

2024-03-10 14:42 UTC, cniackz approved these changes

2024-03-10 14:44 UTC, cniackz commented
I don't think the failure in `Tenant Tests On Kind / Shellcheck (1.21.x) (pull_request) ` has anything to do with these changes. But we can check

2024-03-11 05:32 UTC, shtripat approved these changes
a minor one

2024-03-11 05:32 UTC, shtripat commented on helm/operator/README.md
> +Replace `hostname` by the domain of your external load balancer to interface it with the ingress controller.
I think `replace with` is better wording

2024-03-11 06:21 UTC, harshavardhana commented
Please re-submit with the proper PR Title https://mislav.net/2014/02/hidden-documentation/

2024-03-14 08:50 UTC, jiuker requested changes
TLS have an env for operator, but this pr just set ingress.

2024-03-20 21:05 UTC, closed without merging