Deprecate the Krew plugin
minio/operator pull request #2051
Opened 2024-03-27 23:28 UTC by dvaldivia

We are deprecating the krew plugin in favor of focusing on the `kustomize` and `helm` approach of installing the operator.

2024-03-28 06:16 UTC, shtripat commented
There is an enterprise test using this for expand tenant feature test. We may need to change that.

2024-03-28 12:23 UTC, cniackz submitted a review, later dismissed
LGTM

2024-03-28 12:34 UTC, cniackz commented
Tested and deployed the tenant with this compiled version. It shouldn't break functionality, although I agree with @shtripat  that tests should catch up with the changes, as should the documentation. @ravindk89, please be aware.

<img width="1840" alt="Screenshot 2024-03-28 at 8 32 47 AM" src="https://github.com/minio/operator/assets/6667358/6dc969e1-177d-4962-b197-c67150461f6c">

2024-03-28 12:38 UTC, cniackz commented
Oh I see, tests are updated and regarding `common.sh` these changes looks good to me:

<img width="1369" alt="Screenshot 2024-03-28 at 8 37 31 AM" src="https://github.com/minio/operator/assets/6667358/5d86156f-6cd4-4357-94bd-278145e30a77">

2024-03-28 13:41 UTC, allanrogerr commented
@dvaldivia @cniackz 
This is a breaking change to our users' workflows. Therefore how will this be announced, giving users sufficient time to change their workflows?

2024-03-28 13:42 UTC, allanrogerr requested changes
@dvaldivia @cniackz
This is a breaking change to our users' workflows. Therefore how will this be announced, giving users sufficient time to change their workflows?

2024-03-28 15:10 UTC, ravindk89 commented
@dvaldivia @cniackz if I may suggest:

- Hold this PR for now
- Open a fresh PR that marks all `kubectl minio` commands as deprecated and returns a non-blocking warning on each run (this may break user workflows who parse output in some way)
- Docs will warn that we are deprecating `kubectl minio` route of installation and focus on `kubectl apply -k github.com/minio/operator` and the equivalent for Tenants
- Merge this PR for the subsequent Operator release

With this, we would

- Publish 5.0.15 with a deprecation warning
- Publish 5.0.16 with the deprecation

Users do not always track latest stable that closely, and can stay on 5.0.15 until they have readied their systems to move to Kustomize.

Thoughts?

2024-03-28 16:52 UTC, allanrogerr commented on Makefile
> -plugin: regen-crd
We dont need krew to build and run kubectl-minio . Why is it being removed as well?

2024-03-29 00:10 UTC, harshavardhana approved these changes

2024-03-29 00:12 UTC, harshavardhana commented
> This is a breaking change to our users' workflows. Therefore how will this be announced, giving users sufficient time to change their workflows?

There is no such workflow

2024-03-29 00:12 UTC, harshavardhana commented
> @dvaldivia @cniackz if I may suggest:
> 
> * Hold this PR for now
> * Open a fresh PR that marks all `kubectl minio` commands as deprecated and returns a non-blocking warning on each run (this may break user workflows who parse output in some way)
> * Docs will warn that we are deprecating `kubectl minio` route of installation and focus on `kubectl apply -k github.com/minio/operator` and the equivalent for Tenants
> * Merge this PR for the subsequent Operator release
> 
> With this, we would
> 
> * Publish 5.0.15 with a deprecation warning
> * Publish 5.0.16 with the deprecation
> 
> Users do not always track latest stable that closely, and can stay on 5.0.15 until they have readied their systems to move to Kustomize.
> 
> Thoughts?

No we move to v6.0.0 - we break this and bump the major version.

2024-03-29 12:25 UTC, feorlen commented
What is the timeline for this? It's a major change to how docs describes the k8s install process. We do have some preliminary docs for kustomize in GitHub, but multiple pages in the web docs need rework to feature that instead of krew.

2024-04-05 23:47 UTC, allanrogerr requested changes
Consider the changes to goreleaser made here: https://github.com/minio/operator/pull/2062

2024-04-17 21:32 UTC, cniackz commented
I will solve the conflict:

<img width="434" alt="Screenshot 2024-04-17 at 5 32 10 PM" src="https://github.com/minio/operator/assets/6667358/704fb08d-4658-4c72-bb27-b5970fda1516">

2024-04-17 21:35 UTC, cniackz approved these changes

2024-04-17 21:37 UTC, cniackz commented
The conflict has been resolved, and now I'm awaiting the completion of tests. Once they pass, I'll request the team to review again, and then proceed with the merge.

2024-04-17 21:52 UTC, harshavardhana approved these changes

2024-04-17 21:52 UTC, merged