fix: don't need match number for labels/annotations
minio/operator pull request #2129
Opened 2024-05-23 11:07 UTC by jiuker

fix: don't need match number for labels/annotations

2024-05-24 03:43 UTC, pjuarezd requested changes
Don't remove it, we need to check if labels specified in `.spec.minioServiceLabels` are present, and annotations in `.spec.minioServiceAnnotations` are present. Removing this check is ignore if the secret has expected labels and annotations.

What are you trying to solve?, maybe there is other way to fix it @jiuker

2024-05-24 05:44 UTC, ramondeklein approved these changes
@pjuarezd It’s still checking the labels/annotations, but it only removes the length comparison. It’s not needed, so it’s essentially a code cleanup. Initial PR description is confusing…

A unit test to ensure proper functionality is in place, so LGTM.

2024-05-24 06:19 UTC, pjuarezd commented
> @pjuarezd It’s still checking the labels/annotations, but it only removes the length comparison. It’s not needed, so it’s essentially a code cleanup. Initial PR description is confusing…
> 
> A unit test to ensure proper functionality is in place, so LGTM.

I see, essentially still checks for the service to have the expected labels and annotations without preventing have other additional labels added by a third party controller or manually added.

2024-05-24 06:20 UTC, pjuarezd approved these changes

2024-05-24 06:20 UTC, merged

2024-05-24 06:55 UTC, jiuker commented
> > @pjuarezd It’s still checking the labels/annotations, but it only removes the length comparison. It’s not needed, so it’s essentially a code cleanup. Initial PR description is confusing…
> > A unit test to ensure proper functionality is in place, so LGTM.
> 
> I see, essentially still checks for the service to have the expected labels and annotations without preventing have other additional labels added by a third party controller or manually added.

Yeah.

2024-06-13 22:35 UTC, TZ-zzz commented
Hi, I think the code removed was added in https://github.com/minio/operator/pull/2095 which fixed the issue of labels of service not mtaching the expected labels when deleting labels. Could you explain why this change is no longer necessary?

2024-06-14 00:36 UTC, jiuker commented
Look at the description  @TZ-zzz

2024-06-14 01:01 UTC, TZ-zzz commented
> Look at the description @TZ-zzz

I have looked at description and still not sure why removing length comparison will keep service labels match expected labels when users try to delete existing labels. 

There was a bug that if user deletes existing labels from CR, the operator does not reconcile that change. The code removed in this PR was the fix for that bug.

2024-06-14 01:11 UTC, jiuker commented
Why do you want to delete them?  @TZ-zzz

2024-06-14 01:56 UTC, TZ-zzz commented
@jiuker Add it by mistake. It makes sense to remove the code and allow other operators to add labels directly to the service. If this is intentional, then I have no further questions.

2024-06-14 01:59 UTC, jiuker commented
This is done because there are operators on other networks who can modify the labels and annotations of a service without permission, which is a relatively large scenario and I think it is reasonable @TZ-zzz

2024-06-14 02:09 UTC, TZ-zzz commented
@jiuker I see. Thank you for explaining.