fix: do not create resources for marked deleted tenant
minio/operator pull request #2310
Opened 2024-09-04 07:43 UTC by jiuker

fix: will not create anything for marked deleted tenant

2024-09-04 07:49 UTC, shtripat submitted a review, later dismissed
LGTM. Can we have steps to verify the changes locally?

2024-09-04 13:42 UTC, pjuarezd commented
> > LGTM. Can we have steps to verify the changes locally?
> 
> You can deploy tenant with finalizer. And then delete it @shtripat

which finalizer @jiuker?

2024-09-05 22:01 UTC, pjuarezd requested changes

2024-09-05 22:01 UTC, pjuarezd commented on pkg/controller/main-controller.go
> +		runtime.HandleError(fmt.Errorf("Tenant '%s' is marked for deletion", key))
```suggestion
		runtime.HandleError(fmt.Errorf("Tenant '%s' is marked for deletion, skipping", key))
```

2024-09-11 06:20 UTC, pjuarezd approved these changes

2024-09-11 08:12 UTC, shtripat approved these changes
lgtm

2024-09-11 08:14 UTC, merged