fix: incorrect error log `Waiting for MinIO to be ready: %!s(<nil>)`
minio/operator pull request #2345
Opened 2024-10-18 03:29 UTC by jiuker

fix: incorrect error log
`Waiting for MinIO to be ready: %!s(<nil>)`
fix #2308

2024-10-18 05:41 UTC, shtripat approved these changes
lgtm

2024-10-18 09:26 UTC, ramondeklein requested changes

2024-10-18 09:26 UTC, ramondeklein commented on pkg/controller/main-controller.go
> +		c.recorder.Event(tenant, corev1.EventTypeWarning, WaitingMinIOIsHealthyReason, fmt.Sprintf("Waiting for MinIO(%s/%s) to be ready", tenant.Namespace, tenant.Name))
No need to log the namespace and name. It's logged in the tenant itself, so the namespace/name is already known.
```suggestion
		c.recorder.Event(tenant, corev1.EventTypeWarning, WaitingMinIOIsHealthyReason, "Waiting for MinIO to be ready")
```

2024-10-24 09:38 UTC, shtripat approved these changes

2024-10-25 13:02 UTC, allanrogerr approved these changes
LGTM

2024-10-25 18:15 UTC, cesnietor approved these changes

2024-10-25 18:15 UTC, merged