feat:add portName to container
minio/operator pull request #2347
Opened 2024-10-21 09:10 UTC by jiuker

feat:add portName to container
fix #2326

2024-10-21 09:18 UTC, ramondeklein requested changes
I think we should name all ports if we start to name one. I don't think this can potentially break anything?

2024-10-21 09:18 UTC, ramondeklein commented on pkg/resources/statefulsets/minio-statefulset.go
> +			Name:          miniov2.MinIOPortName,
If we name the MinIO port, then it makes sense to also name the console port (a few lines down).

2024-10-21 09:53 UTC, ramondeklein approved these changes

2024-10-21 09:58 UTC, shtripat approved these changes

2024-10-25 13:01 UTC, allanrogerr approved these changes
LGTM

2024-10-25 13:03 UTC, merged