Remove MinIO Tenant Labels From Console Pods
minio/operator pull request #323
Opened 2020-10-07 23:51 UTC by dvaldivia

This PR removes the `v1.min.io/tenant` label from the Console pods, it was added so that ownership of a console pod could be determined via it's tenant label, but this had the side effect that the Tenant service started targeting the console pods, thus causing that 1 out of every X calls (where X is the number of MinIO Pods + 1) to fail.

2020-10-07 23:53 UTC, Alevsk submitted a review, later dismissed

2020-10-07 23:56 UTC, harshavardhana requested changes
Can this be fixed for kubectl plugin as well ? - we seem to be having these things duplicated.

2020-10-08 01:21 UTC, dvaldivia commented
@harshavardhana no need, I already checked and `ConsoleTenantLabel` is only used in once place, and then `ConsolePodLabels()` is used everywhere else, I don't see the plugin duplicating this code

2020-10-08 01:44 UTC, Alevsk commented
```
func KESMetadata(t *miniov1.Tenant) metav1.ObjectMeta {
	meta := metav1.ObjectMeta{}
	meta.Labels = t.Spec.KES.Labels
	meta.Annotations = t.Spec.KES.Annotations

	if meta.Labels == nil {
		meta.Labels = make(map[string]string)
	}
	for k, v := range t.KESPodLabels() {
		meta.Labels[k] = v
	}
	meta.Labels[miniov1.TenantLabel] = t.Name
	return meta
}
```

`kes-statefulset.go` also has the label

2020-10-08 02:09 UTC, Alevsk approved these changes

2020-10-08 02:19 UTC, harshavardhana approved these changes

2020-10-08 02:19 UTC, merged