Improve debug print when tar file extraction fails
minio/operator pull request #331
Opened 2020-10-10 00:25 UTC by kerneltime

I tried to update the tenant image with a development build that was uploaded to docker hub and that failed during tar file extraction. Improved the debug print to help.

2020-10-11 15:29 UTC, nitisht requested changes

2020-10-11 15:29 UTC, nitisht commented on pkg/apis/minio.min.io/v1/helper.go
> +			return fmt.Errorf("Tar file extraction failed to find next: %d, %w", success, err)
```suggestion
			return fmt.Errorf("Tar file extraction failed for file index: %d, with: %w", success, err)
```

2020-10-11 15:29 UTC, nitisht commented on pkg/apis/minio.min.io/v1/helper.go
> +					return fmt.Errorf("Tar file extraction failed during open: %d, %s, %w", success, name, err)
```suggestion
					return fmt.Errorf("Tar file extraction failed while opening file: %s, at index: %d, with: %w", name, success, err)
```

2020-10-11 15:29 UTC, nitisht commented on pkg/apis/minio.min.io/v1/helper.go
> +					return fmt.Errorf("Tar file extraction failed during copy: %d, %s, %w", success, name, err)
```suggestion
					return fmt.Errorf("Tar file extraction failed while copying file: %s, at index: %d, with: %w", name, success, err)
```

2020-10-11 18:46 UTC, harshavardhana approved these changes

2020-10-12 01:11 UTC, nitisht approved these changes

2020-10-12 01:12 UTC, merged