Create tenant-lite.yaml
minio/operator pull request #491
Opened 2021-02-23 21:55 UTC by sips4711

Created a Lite Tenant for smaller environments to prevent screwing up the storage system.

2021-02-24 21:24 UTC, Alevsk requested changes

2021-02-24 21:24 UTC, Alevsk commented on examples/tenant-lite.yaml
> +  image: minio/minio:RELEASE.2021-02-19T04-38-02Z
```suggestion
  image: minio/minio:RELEASE.2021-02-24T18-44-45Z 
```

2021-02-25 18:39 UTC, Alevsk approved these changes

2021-02-25 23:04 UTC, harshavardhana approved these changes

2021-02-25 23:04 UTC, merged