Switch to Go 1.16, Remove Statik and switch to Embed
minio/operator pull request #516
Opened 2021-03-04 19:20 UTC by dvaldivia

Removes the dependency on statik, we still need to copy the resources around sadly, but now we use the native `embed` for embedding static files

2021-03-04 19:20 UTC, dvaldivia commented on kubectl-minio/cmd/resources/common.go
> +var fs embed.FS
this is the new special sauce

2021-03-04 19:25 UTC, harshavardhana requested changes

2021-03-04 19:25 UTC, harshavardhana commented on Makefile
>  statik:
```suggestion
embed:
```

2021-03-04 19:36 UTC, harshavardhana requested changes

2021-03-04 19:36 UTC, harshavardhana commented on resources/assets.go
> +package resources
```suggestion
package assets
```

2021-03-05 16:10 UTC, bexsoft approved these changes
LGTM

2021-03-05 16:20 UTC, harshavardhana approved these changes

2021-03-06 08:27 UTC, nitisht approved these changes
LGTM & Tested

2021-03-06 08:28 UTC, merged