Update CRD Autogenerated Documentation Reference
minio/operator pull request #521
Opened 2021-03-06 01:12 UTC by ravindk89

# Goals

- Update the CRD comment reference in `types.go` to be more descriptive of what each field is, how to use it, etc.
- Include links to the "Full" MinIO K8s documentation where appropriate
- Include links to examples where appropriate (some temporary until full K8s docs are more mature)
- Remove v1 API reference and prominently mark it as 'deprecated'. 

# Non Goals
- Fix the Go CommentBody behavior to support more asciidoc syntax
- Provide complete examples for each section
- Modify the CRD code itself in any meaningful user-impacting way.

There's a lot here, so let me know if there are any questions. One big note is I had to make a few guesses as to what fields are Optional or Required based on our existing examples and what I could glean from the code. Leave a comment for any field where I've made a mistake on that part.

One note - the `gv_list.tpl` file now contains some variables for the Docker images used by our various properties. It was easier to define them in a single place so we can update the images as we go along from a single (much smaller) file.

2021-03-06 01:31 UTC, ravindk89 commented
Looks like the Linter didn't like some of my changes. I'll go through and fix those areas.

2021-03-09 00:06 UTC, ravindk89 commented
@dvaldivia I've rebased to include the latest changes and updated the PrometheusConfig docs to include the deprecation warnings as discussed.

2021-03-09 09:42 UTC, harshavardhana approved these changes

2021-03-09 09:45 UTC, harshavardhana requested changes

2021-03-09 09:45 UTC, harshavardhana commented on docs/templates/asciidoctor/gv_list.tpl
> +:logsearch-image: https://hub.docker.com/r/minio/logsearchapi/tags[minio/logsearchapi:v4.0.1]
```suggestion
:logsearch-image: https://hub.docker.com/r/minio/logsearchapi/tags[minio/logsearchapi:v4.0.2]
```

2021-03-09 09:46 UTC, harshavardhana requested changes

2021-03-09 09:46 UTC, harshavardhana commented on docs/crd.adoc
> +:logsearch-image: https://hub.docker.com/r/minio/logsearchapi/tags[minio/logsearchapi:v4.0.1]
```suggestion
:logsearch-image: https://hub.docker.com/r/minio/logsearchapi/tags[minio/logsearchapi:v4.0.2]
```

2021-03-09 09:46 UTC, harshavardhana submitted a review, later dismissed

2021-03-09 13:21 UTC, nitisht submitted a review, later dismissed
LGTM 👍🏽

2021-03-09 16:31 UTC, ravindk89 commented
@nitisht @harshavardhana can you do a cursory LGTM? I rebased to remove the merge commit and squashed down.

2021-03-09 17:53 UTC, harshavardhana approved these changes

2021-03-09 17:54 UTC, merged