Added tenant configuration to helm-chart
minio/operator pull request #526
Opened 2021-03-08 00:29 UTC by abhi1693

In my environment, there is no easy way to use `kubectl`, `kustomize`, or `krew`. However, if the deployment is done via `helm` chart, then I can manage using our automation tools.

Hopefully, this PR will get accepted for merge and would help many others as well to deploy MinIO much easily.

2021-03-08 04:07 UTC, nitisht commented
Thanks @abhi1693 looks interesting. We'll review and test soon.

2021-03-08 04:54 UTC, nitisht commented
@abhi1693 There is one issue with the approach here:

The `values.yaml` file doesn't really make it clear that while some parts (operator related) are single / one time operations only. The other parts. i.e. tenant related can be appended with a new tenant configuration every time someone wants to create a new tenant. 

Can we make the tenant part in the values.yaml like a yaml array? Also add some comments on what each part in the file is supposed to do.

2021-03-08 05:13 UTC, abhi1693 commented
@nitisht I'll update the comments once you ensure that everything else looks good. The values.yaml is loosely based on examples/tenant.yaml file at the moment.

2021-03-11 07:20 UTC, nitisht requested changes
@abhi1693 Thanks for the changes. I was trying to deploy but the helm install fails with

```
Error: template: minio-operator/templates/tenant-secret.yaml:8:23: executing "minio-operator/templates/tenant-secret.yaml" at <.Values.tenant.secrets.accessKey>: nil pointer evaluating interface {}.secrets
```

2021-03-11 07:25 UTC, nitisht commented on helm/minio-operator/templates/tenant.yaml
> +      name: console-secret
Console-secret should be a user input as well.

2021-03-11 07:25 UTC, nitisht commented on helm/minio-operator/templates/tenant.yaml
> +{{ end }}
newline

2021-03-11 07:25 UTC, nitisht commented on helm/minio-operator/values.yaml
> +      replicaCount: 1
newline

2021-03-11 07:25 UTC, nitisht commented on helm/minio-operator/values.yaml
> +      s3:
`s3` can be a top level field, i.e. at par with `certificate`

2021-03-11 07:25 UTC, nitisht commented on helm/minio-operator/values.yaml
> +  secrets:
This console section is for operator console. These secrets have to be added to a new `console` section under tenants

2021-03-11 07:25 UTC, nitisht commented on helm/minio-operator/templates/console-secret.yaml
> +  CONSOLE_SECRET_KEY: {{ .Values.console.secrets.secretKey }}
newline

2021-03-11 07:25 UTC, nitisht commented on helm/minio-operator/templates/tenant-secret.yaml
> +  secretkey: {{ .Values.tenant.secrets.secretkey }}
newline

2021-03-11 12:45 UTC, abhi1693 commented
@nitisht I have a suggestion to avoid future template deploy failures. Can you add a GitHub action workflow that uses `kubeval` and `helm template` commands to verify the configuration?

The command is: 
```
helm template --values "$chart_path/values.yaml" "$chart_path" | kubeval --strict --exit-on-error --output tap
```

2021-03-11 12:46 UTC, abhi1693 commented
@nitisht Can you also add another GitHub workflow to update the documentation automatically for any changed value in values.yaml using `helm-docs`?

2021-03-15 05:13 UTC, nitisht commented
Have you tested this @abhi1693 ? I see this error when running it 

```
$ helm install ./minio-operator/ --generate-name --create-namespace --namespace minio-operator
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Tenant" in version "minio.min.io/v2"

```

2021-03-15 06:45 UTC, abhi1693 commented
@nitisht I have fixed the issue for now, but you will have to make sure that the crd is always placed under `crds` directory. But this will again not work if the file is placed by your team under `templates`

2021-03-15 08:00 UTC, nitisht commented
There are some more fixes to be done, I'll send a PR to your fork. We can proceed from there

2021-03-16 08:44 UTC, nitisht commented
can you take this https://github.com/abhi1693/operator/pull/1 @abhi1693 ?

2021-03-16 08:59 UTC, nitisht approved these changes
LGTM, basic testing working.

2021-03-17 03:00 UTC, harshavardhana approved these changes

2021-03-17 03:00 UTC, merged