Add support for ServiceMonitor object per Tenant
minio/operator pull request #544
Opened 2021-03-23 15:12 UTC by nitisht

2021-03-23 15:14 UTC, harshavardhana requested changes

2021-03-23 15:14 UTC, harshavardhana commented on resources/deployment.yaml
> +          image: nitishtiwari/operator:sm
```suggestion
          image: nitishtiwari/operator:sm
```

??

2021-03-31 16:15 UTC, harshavardhana submitted a review, later dismissed

2021-04-01 14:35 UTC, nitisht commented on pkg/apis/minio.min.io/v2/helper.go
> +		Issuer:    "prometheus",
no it should be `prometheus` since the MinIO server is looking for `Issuer:    "prometheus",`

2021-04-01 20:34 UTC, krisis approved these changes

2021-04-01 21:55 UTC, harshavardhana approved these changes

2021-04-01 21:55 UTC, merged