Add supports for KES changes detection
minio/operator pull request #552
Opened 2021-03-25 00:03 UTC by Alevsk

This PR adds support for changes on the KES configuration such as
changing image version or number of replicas

Fixes https://github.com/minio/operator/issues/543

2021-03-25 10:42 UTC, aead submitted a review, later dismissed

2021-03-25 21:03 UTC, dvaldivia requested changes

2021-03-25 21:08 UTC, Alevsk commented on pkg/controller/cluster/kes.go
> +// kesStatefulSetMatchesSpec checks if the StatefulSet for KES matches what is expected and described from the Tenant
`!equality.Semantic.DeepDerivative(expectedStatefulSet.Spec, kesStatefulSet.Spec)` should take care of that correct?

2021-03-27 19:46 UTC, dvaldivia approved these changes

2021-03-29 10:47 UTC, nitisht approved these changes

2021-03-29 10:47 UTC, merged