Fix Kustomize at root level
minio/operator pull request #583
Opened 2021-04-13 19:41 UTC by dvaldivia

Fixes installing operator using `kubectl apply -k github.com/minio/operator/\?ref\=v4.0.6` which I broke via https://github.com/minio/operator/pull/548

the current problem is that `kubectl` still hips kustomize 2x https://github.com/kubernetes/kubectl/issues/818

2021-04-13 19:43 UTC, harshavardhana approved these changes

2021-04-13 19:43 UTC, harshavardhana requested changes

2021-04-13 19:43 UTC, harshavardhana commented on kustomization.yaml
> -  - resources/
```
- resources/*
```

doesn't work? @dvaldivia

2021-04-13 19:45 UTC, dvaldivia commented on kustomization.yaml
> -  - resources/
sadly no, `kubectl apply -k` yields 
```
error: rawResources failed to read Resources: Load from path resources/ failed: 'resources/' must be a file (got d='/Users/dvaldivia/go/src/github.com/minio/operator/resources')
```

2021-04-13 19:47 UTC, dvaldivia commented on kustomization.yaml
> -  - resources/
```
error: rawResources failed to read Resources: Load from path resources/* failed: evalsymlink failure on '/Users/dvaldivia/go/src/github.com/minio/operator/resources/*' : lstat /Users/dvaldivia/go/src/github.com/minio/operator/resources/*: no such file or directory
```
if we use `resources/*`

2021-04-15 15:53 UTC, harshavardhana approved these changes

2021-04-16 21:27 UTC, merged