Add CSV file for RedHat OpenShift validation
minio/operator pull request #630
Opened 2021-05-10 07:35 UTC by nitisht

2021-05-13 03:06 UTC, harshavardhana requested changes
Can you update this for v4.0.10 release?

2021-05-20 10:18 UTC, nitisht commented
> Can you update this for v4.0.10 release?

Updated to v4.0.11

2021-05-26 00:12 UTC, harshavardhana approved these changes

2021-05-26 13:53 UTC, dvaldivia approved these changes

2021-05-26 15:37 UTC, merged