[Don't Merge] Autocert refactor
minio/operator pull request #668
Opened 2021-06-08 02:01 UTC by Alevsk

2021-06-08 19:20 UTC, dvaldivia requested changes

2021-06-08 19:20 UTC, dvaldivia commented on pkg/controller/cluster/monitoring.go
> +		//DialContext: (&net.Dialer{
perhaps remove this commented code

2021-06-14 18:05 UTC, dvaldivia approved these changes
Tested. LGTM.

2021-06-14 23:05 UTC, harshavardhana commented on pkg/controller/cluster/pools.go
> +		}
👍🏽  nice

2021-06-14 23:05 UTC, harshavardhana approved these changes

2021-06-15 00:00 UTC, merged