Add nodeSelector and other options to Tenant console pods
minio/operator pull request #695
Opened 2021-06-28 08:43 UTC by nitisht

2021-06-28 11:17 UTC, dnskr commented on helm/minio-operator/values.yaml
> +      tolerations: ()
should it be  `tolerations: []` instead of `tolerations: ()` ?

2021-06-28 16:21 UTC, harshavardhana requested changes

2021-06-28 16:21 UTC, harshavardhana commented on helm/minio-operator/values.yaml
> +      env: {}
```suggestion
      env: {}

```

2021-06-28 16:21 UTC, harshavardhana commented on helm/minio-operator/values.yaml
> +      tolerations: ()
```suggestion
      tolerations: []
```

2021-06-29 07:00 UTC, harshavardhana approved these changes

2021-06-30 15:19 UTC, Praveenrajmani approved these changes

2021-06-30 15:21 UTC, merged