[WIP] Add support for tenant Configuration file
minio/operator pull request #724
Opened 2021-07-15 02:14 UTC by Alevsk

2021-07-26 23:53 UTC, harshavardhana requested changes
Also not sure why you are spending time on getting console updated? @Alevsk - perhaps you should work with @nitisht to get the `console` pod removed from the deployment.

We can merge this change on top of @nitisht change

2021-07-26 23:53 UTC, harshavardhana commented on examples/tenant-lite.yaml
> +              storage: 1Gi
Keep this 100Gi

2021-07-27 00:47 UTC, Alevsk commented on examples/tenant-lite.yaml
> +              storage: 1Gi
fixed

2021-07-27 16:19 UTC, bexsoft requested changes

2021-07-27 16:19 UTC, bexsoft commented on examples/tenant-lite.yaml
> +  image: alevsk/minio:env
Is this ok?

2021-07-28 23:51 UTC, bexsoft approved these changes

2021-07-29 17:36 UTC, dvaldivia approved these changes

2021-08-02 17:26 UTC, dvaldivia submitted a review, later dismissed

2021-08-02 17:58 UTC, bexsoft approved these changes

2021-08-03 00:50 UTC, harshavardhana approved these changes

2021-08-03 00:55 UTC, bexsoft approved these changes

2021-08-03 01:20 UTC, dvaldivia approved these changes

2021-08-03 01:20 UTC, merged