Release v4.2.0
minio/operator pull request #774
Opened 2021-08-18 21:28 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-08-18 21:32 UTC, harshavardhana requested changes

2021-08-18 21:32 UTC, harshavardhana commented on manifests/minio-operator.v4.1.2.clusterserviceversion.yaml
> +  name: minio-operator.v4.1.3
```suggestion
  name: minio-operator.v4.2.0
```

2021-08-18 22:25 UTC, bexsoft approved these changes

2021-08-18 22:41 UTC, Alevsk approved these changes

2021-08-19 00:27 UTC, Alevsk approved these changes

2021-08-19 00:42 UTC, bexsoft approved these changes

2021-08-19 01:59 UTC, bexsoft submitted a review, later dismissed

2021-08-19 04:10 UTC, Alevsk submitted a review, later dismissed

2021-08-19 06:59 UTC, harshavardhana requested changes

2021-08-19 06:59 UTC, harshavardhana commented on pkg/controller/cluster/operator.go
> +	return DefaultDeploymentName
```suggestion
        return env.Get("MINIO_OPERATOR_DEPLOYMENT_NAME", DefaultDeploymentName)
```

2021-08-22 05:12 UTC, harshavardhana approved these changes

2021-08-22 05:13 UTC, merged