Confirm runnning Pools before restarting existing pools
minio/operator pull request #777
Opened 2021-08-20 06:43 UTC by dvaldivia

This makes sure we can reach the first pod of a pool before telling other pools to restart to account for the new pool, this is to avoid a deadlock  where minio becomes non-functional and the statefulsets are never updated.

Also makes it so we create the log search secret before creating ss since we may reference them

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-08-20 17:11 UTC, Alevsk approved these changes

2021-08-22 04:28 UTC, bexsoft requested changes

2021-08-22 04:28 UTC, bexsoft commented on pkg/controller/cluster/monitoring.go
> +		klog.Infof("dos")
Please remove this

2021-08-22 04:28 UTC, bexsoft commented on pkg/controller/cluster/monitoring.go
> +		klog.Infof("dos.5 %+v", storageInfo)
Please remove this

2021-08-22 04:28 UTC, bexsoft commented on pkg/controller/cluster/monitoring.go
> +		klog.Infof("trres")
Please remove this

2021-08-22 04:28 UTC, bexsoft commented on pkg/controller/cluster/monitoring.go
> +		klog.Infof("safe")
Please remove this

2021-08-22 05:38 UTC, dvaldivia commented on pkg/controller/cluster/monitoring.go
> +		klog.Infof("dos")
removed

2021-08-22 05:38 UTC, dvaldivia commented on pkg/controller/cluster/monitoring.go
> +		klog.Infof("dos.5 %+v", storageInfo)
removed

2021-08-22 05:38 UTC, dvaldivia commented on pkg/controller/cluster/monitoring.go
> +		klog.Infof("trres")
removed

2021-08-22 05:39 UTC, dvaldivia commented on pkg/controller/cluster/monitoring.go
> +		klog.Infof("safe")
removed

2021-08-22 06:38 UTC, bexsoft approved these changes

2021-08-22 17:40 UTC, Alevsk approved these changes

2021-08-22 19:41 UTC, merged