Release v4.2.2
minio/operator pull request #785
Opened 2021-08-24 04:51 UTC by dvaldivia

- MinIO: `minio/minio:RELEASE.2021-08-20T18-32-01Z`
- Console: `v0.9.3`

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-08-24 05:56 UTC, harshavardhana approved these changes

2021-08-24 16:40 UTC, Alevsk approved these changes

2021-08-24 16:43 UTC, bexsoft submitted a review, later dismissed

2021-08-24 16:57 UTC, harshavardhana requested changes
Wait we are making a new MinIO release

2021-08-24 16:58 UTC, Alevsk commented
> Wait we are making a new MinIO release

ill test with the new MinIO release then

2021-08-24 17:00 UTC, dvaldivia commented
@harshavardhana I think @Alevsk wants to make another operator release later today xD

2021-08-24 23:31 UTC, Alevsk submitted a review, later dismissed

2021-08-24 23:32 UTC, bexsoft submitted a review, later dismissed

2021-08-25 02:04 UTC, harshavardhana requested changes

2021-08-25 02:04 UTC, harshavardhana commented on docs/crd.adoc
> +:minio-image: https://hub.docker.com/r/minio/minio/tags[minio/minio:RELEASE.2021-08-20T18-32-01Z]
```suggestion
:minio-image: https://hub.docker.com/r/minio/minio/tags[minio/minio:RELEASE.2021-08-25T00-41-18Z]
```

2021-08-25 02:04 UTC, harshavardhana commented on docs/templates/asciidoctor/gv_list.tpl
> +:minio-image: https://hub.docker.com/r/minio/minio/tags[minio/minio:RELEASE.2021-08-20T18-32-01Z]
```suggestion
:minio-image: https://hub.docker.com/r/minio/minio/tags[minio/minio:RELEASE.2021-08-25T00-41-18Z]
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-encryption.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-lite.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-log-search.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-pod-security-policy.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-prometheus.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-tiny.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-with-autocert-and-custom-certs-encryption-enabled.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-with-autocert-and-ldap.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:04 UTC, harshavardhana commented on examples/tenant-with-autocert-encryption-disabled.yaml
> +  image: minio/minio:RELEASE.2021-08-20T18-32-01Z
```suggestion
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
```

2021-08-25 02:58 UTC, harshavardhana approved these changes

2021-08-25 02:59 UTC, merged