Return CSR to use api v1beta1
minio/operator pull request #825
Opened 2021-09-10 21:49 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-09-10 21:57 UTC, harshavardhana requested changes

2021-09-10 21:57 UTC, harshavardhana commented on pkg/controller/cluster/csr.go
> +			//SignerName: csrSignerName,
why are all these commented?

2021-09-10 22:04 UTC, Alevsk requested changes
testing all this

2021-09-12 07:58 UTC, dvaldivia commented on pkg/controller/cluster/csr.go
> +			//SignerName: csrSignerName,
done

2021-09-12 08:00 UTC, Alevsk approved these changes
Tested on 1.17 - 1.22 k8s

2021-09-12 08:24 UTC, harshavardhana approved these changes

2021-09-12 18:47 UTC, merged