Adding tenant-debug to store logs and events
minio/operator pull request #846
Opened 2021-09-22 17:16 UTC by adfost

Adding tenant-debug, a command that stores logs and events for pods in a zip file.

2021-09-22 17:29 UTC, harshavardhana requested changes

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +}
```suggestion
}

```

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +	w, err := os.Create("dump.zip")
take the tenant name here and call it `<tenant>-report.zip`

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +			return err
Any failure here make sure to delete the `tenant-report.zip`

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +			return err
Any failure here make sure to delete the `tenant-report.zip`

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +			return err
Any failure here make sure to delete the `tenant-report.zip`

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +	w, err := os.Create("dump.zip")
Make sure to also open the file in `O_SYNC` to make sure to avoid any partial values stored

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +		Use:   "debug",
```suggestion
		Use:   "report",
```

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +func newTenantDebugCmd(out io.Writer, errOut io.Writer) *cobra.Command {
```suggestion
func newTenantReportCmd(out io.Writer, errOut io.Writer) *cobra.Command {
```

2021-09-22 17:29 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-debug.go
> +		Short: "Save pod logs, events, and status for a tenant",
```suggestion
		Short: "Collect pod logs, events, and status for a tenant",
```

2021-09-23 17:51 UTC, harshavardhana requested changes

2021-09-23 17:51 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-report.go
> +			klog.Info("info tenant command started")
```suggestion
			klog.Info("report tenant command started")
```

2021-09-23 17:51 UTC, harshavardhana commented on kubectl-minio/cmd/tenant-report.go
> +		return errors.New("info command supports a single argument, e.g. 'kubectl minio tenant info tenant1'")
```suggestion
		return errors.New("report command supports a single argument, e.g. 'kubectl minio tenant report tenant1'")
```

2021-09-23 22:37 UTC, dvaldivia commented
I don't see the new command in the CLI
```
➜ ./kubectl-minio tenant debug

'tenant' is the top level command for managing MinIO tenants created via operator.

Usage:
  minio tenant [command]

Available Commands:
  create      Create a MinIO tenant
  info        List all volumes in existing tenant
  list        List all tenants
  expand      Add capacity to existing tenant
  upgrade     Upgrade MinIO image for existing tenant
  delete      Delete a MinIO tenant

Flags:
  -h, --help   help for tenant

Global Flags:
      --kubeconfig string   Custom kubeconfig path

Use "minio tenant [command] --help" for more information about a command.
 kubectl-minio git:(8103271) ✗ 

```

2021-09-23 23:26 UTC, dvaldivia requested changes
If I try to get the report while a single pod is pending, the command fails with error

```
➜ ./kubectl-minio tenant report warm-tier-storage -n ns-4
Error: the server rejected our request for an unknown reason (get pods warm-tier-storage-pool-0-0)
```

2021-09-25 00:48 UTC, dvaldivia approved these changes

2021-09-25 01:05 UTC, harshavardhana approved these changes

2021-09-25 01:05 UTC, merged