Split Helm Chart into separate Charts
minio/operator pull request #918
Opened 2021-12-03 04:10 UTC by dvaldivia

This PR splits the current helm chart `minio/minio-operator` into two charts `minio/operator` and `minio/tenant`

This is to decouple changes to an individual tenant and upgrades to the operator for simplicity of operations.

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-12-03 04:22 UTC, harshavardhana commented
> ```shell
> helm install \helm install \
>   --namespace default  \
>   --create-namespace \
>   minio-operator \
>   ./helm/tenant
> ```

Is this correct? @dvaldivia

2021-12-03 21:10 UTC, harshavardhana requested changes

2021-12-03 21:10 UTC, harshavardhana commented on helm/tenant/README.md
> +```
This should provide the same docs referencing the `repo` not local file

2021-12-07 20:50 UTC, harshavardhana requested changes

2021-12-07 20:50 UTC, harshavardhana commented on docs/crd.adoc
> +:minio-image: https://hub.docker.com/r/minio/minio/tags[minio/minio:RELEASE.2021-11-24T23-19-33Z]
```suggestion
:minio-image: https://hub.docker.com/r/minio/minio/tags[minio/minio:RELEASE.2021-11-24T23-19-33Z]
```

No change is needed to this version yet - let's keep the default with the previous version for now - we will move to a newer release this week instead.

2021-12-08 22:21 UTC, harshavardhana approved these changes

2021-12-09 14:24 UTC, kanagarajkm approved these changes
LGTM, one minor comment

2021-12-09 23:08 UTC, merged

2022-02-09 05:08 UTC, walkafwalka commented
Is there a migration path for users who are already using the combined operator chart?

2022-02-09 06:42 UTC, harshavardhana commented
> Is there a migration path for users who are already using the combined operator chart?

@walkafwalka unfortunately no.