create prometheus addl config for prometheus-operator
minio/operator pull request #920
Opened 2021-12-06 13:31 UTC by kanagarajkm

- Removed ServiceMonitor. Using ServiceMonitor leads to prometheus scrapping all the pods for the cluster level metrics which is not desired
- Additional scrape config will be added to `Prometheus` resource when `prometheusOperator` is enabled for a tenant

2021-12-07 00:02 UTC, harshavardhana requested changes
This would require CRD updates @kanagarajkm - don't see them in the PR?

2021-12-07 00:02 UTC, harshavardhana commented on pkg/controller/cluster/main-controller.go
> +		klog.Infof("Adding Prometheus addl config")
```suggestion
		klog.Infof("Adding MinIO tenant Prometheus scrape config")
```

2021-12-07 00:02 UTC, harshavardhana commented on pkg/controller/cluster/main-controller.go
> +		klog.Infof("Deleting Prometheus addl config")
```suggestion
		klog.Infof("Deleting MinIO tenant Prometheus scrape config"")
```

2021-12-07 00:02 UTC, harshavardhana commented on resources/base/cluster-role.yaml
>        - servicemonitors
We need to remove 

```suggestion
```

2021-12-07 06:51 UTC, kanagarajkm commented
@harshavardhana i have updated the CRD, please take a look.

2021-12-07 07:51 UTC, harshavardhana approved these changes
LGTM haven't tested yet

2021-12-09 23:20 UTC, dvaldivia submitted a review, later dismissed

2021-12-21 06:36 UTC, harshavardhana commented
@kanagarajkm can you fix the conflicts?

2021-12-22 13:43 UTC, kanagarajkm commented
@harshavardhana i have fixed the conflicts, PTAL

2021-12-23 08:35 UTC, harshavardhana approved these changes

2021-12-27 07:10 UTC, harshavardhana commented
PTAL @dvaldivia

2021-12-27 22:39 UTC, dvaldivia approved these changes

2021-12-27 22:50 UTC, merged

2024-02-25 18:46 UTC, fionera commented
Why was this done instead of modifying the scrape config to only scrape one of the instances for these metrics. The new approach does not work with any other setup except one case where you have only a prometheus in a specific namespace. As I understand it I cannot have a seperate prometheus instance per tenant and support for using PrometheusAgent is completely missing

2024-11-22 18:56 UTC, chriskhanhtran commented
> Why was this done instead of modifying the scrape config to only scrape one of the instances for these metrics. The new approach does not work with any other setup except one case where you have only a prometheus in a specific namespace. As I understand it I cannot have a seperate prometheus instance per tenant and support for using PrometheusAgent is completely missing

@fionera 
> Starting with prometheus-operator v0.65.x, one can use the ScrapeConfig CRD to scrape targets external to the Kubernetes cluster or create scrape configurations that are not possible with the higher level ServiceMonitor/Probe/PodMonitor resources. (source: https://prometheus-operator.dev/docs/developer/scrapeconfig/)

I think creating ScrapeConfig CR is a better and neater way to add scrape config, instead of using MinIO operator to modify Prometheus CR, which could be managed by Helm/Terraform.