Basic Tenant deployment script
minio/operator pull request #953
Opened 2022-01-03 20:56 UTC by dvaldivia

Basic script to test a tenant can be created

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-01-03 22:52 UTC, harshavardhana requested changes

2022-01-03 22:52 UTC, harshavardhana commented on testing/basic-tenant.sh
> +while :; do
```suggestion
while true; do
```

Let's use readable values.

2022-01-03 22:52 UTC, harshavardhana commented on testing/basic-tenant.sh
> +while :; do
```suggestion
while true; do
```

2022-01-03 22:52 UTC, harshavardhana commented on testing/basic-tenant.sh
> +  if [ "$totalwait" -gt 300 ]; then
```suggestion
  if [ "$totalwait" -gt 305 ]; then
```

2022-01-03 22:52 UTC, harshavardhana commented on testing/basic-tenant.sh
> +    echo "Tenant never created statefulset after 5 minutes"
```suggestion
    echo "Unable to create tenant after 5 minutes, exiting."
```

2022-01-03 22:52 UTC, harshavardhana commented on testing/basic-tenant.sh
> +  waitdone=$(kubectl -n tenant-lite get pods -o json | jq '.items | length')
```suggestion
  waitdone=$(kubectl -n tenant-lite get pods -l v1.min.io/tenant=tenant-lite --no-headers | wc -l)
```

isn't this simpler?

2022-01-03 22:52 UTC, harshavardhana commented on testing/basic-tenant.sh
> +die() {
```suggestion

die() {
```

2022-01-03 22:52 UTC, harshavardhana commented on testing/basic-tenant.sh
> +try() { "$@" || die "cannot $*"; }
```suggestion

try() { "$@" || die "cannot $*"; }
```

2022-01-04 02:18 UTC, cniackz commented on testing/basic-tenant.sh
> +  --selector="v1.min.io/tenant=tenant-lite" \
This selector is not working, by looking at the pod's labels, we should be using below selector:
`--selector="v1.min.io/tenant=storage-lite"`
Notice this time is using "storage" and not "tenant" 
I got the labels with command below:
`kubectl get pods --show-labels -n tenant-lite`
And I assume, we want to wait for these pods:

- storage-lite-ss-0-0
- storage-lite-ss-0-1
- storage-lite-ss-0-2
- storage-lite-ss-0-3

2022-01-04 16:16 UTC, cniackz requested changes
The same applies for `-l v1.min.io/tenant=tenant-lite` where the selector is wrong.
It should be `-l v1.min.io/tenant=storage-lite` as per the node label.

2022-01-04 16:16 UTC, cniackz commented on testing/basic-tenant.sh
> +  waitdone=$(kubectl -n tenant-lite get pods -l v1.min.io/tenant=tenant-lite --no-headers | wc -l)
The same applies for `-l v1.min.io/tenant=tenant-lite` where the selector is wrong.
It should be `-l v1.min.io/tenant=storage-lite`

2022-01-04 20:03 UTC, cniackz commented on testing/basic-tenant.sh
> +  --selector="v1.min.io/tenant=tenant-lite" \
Added new commit on top of this pull request to solve the issue

2022-01-04 20:04 UTC, cniackz commented on testing/basic-tenant.sh
> +  waitdone=$(kubectl -n tenant-lite get pods -l v1.min.io/tenant=tenant-lite --no-headers | wc -l)
Added new commit on top of the pull request to solve the problem

2022-01-04 20:11 UTC, cniackz submitted a review, later dismissed
The script is now working when is executed

2022-01-04 23:43 UTC, dvaldivia commented on .github/workflows/bash.yml
> +    branches: [ main ]
```suggestion
    branches: [ master ]
```

2022-01-04 23:43 UTC, dvaldivia commented on .github/workflows/bash.yml
> +    branches: [ main ]
```suggestion
    branches: [ master ]
```

2022-01-04 23:50 UTC, harshavardhana approved these changes

2022-01-05 00:10 UTC, merged