replace sigs/yaml to go/yaml for a more spec compliant yaml library
minio/operator pull request #996
Opened 2022-01-30 20:49 UTC by harshavardhana

continuation of an issue seen in #990

2022-01-31 16:04 UTC, kanagarajkm approved these changes

2022-02-01 02:23 UTC, dvaldivia requested changes
The output of serializing with `gopkg.in/yaml.v2` is radically different from the one from `sigs.k8s.io/yaml`, and the output is incompatible with `kubectl apply -f` so not good 

<img width="1536" alt="Screen Shot 2022-01-31 at 6 23 31 PM" src="https://user-images.githubusercontent.com/18384552/151904297-c0406f9b-e5fc-453e-af3d-25085af1a6ab.png">

2022-02-01 03:43 UTC, dvaldivia submitted a review, later dismissed

2022-02-01 05:53 UTC, harshavardhana commented
PTAL @dvaldivia @kanagarajkm

2022-02-01 14:13 UTC, kanagarajkm commented
@harshavardhana prometheus is failing with following error

```
ts=2022-02-01T14:10:12.900Z caller=main.go:434 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" err="parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 4: field Global not found in type config.plain\n  line 7: field ScrapeConfigs not found in type config.plain"
```

```
apiVersion: v1
data:
  prometheus.yml: |
    # This file and config-map is generated by MinIO Operator.
    # DO NOT EDIT.

    Global:
      EvaluationInterval: 30000000000
      ScrapeInterval: 30000000000
    ScrapeConfigs:
    - BearerToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ3OTczMjQ0MjIsImlzcyI6InByb21ldGhldXMiLCJzdWIiOiIwSUkwS0lMVjJLWldZVFFKIn0.GUY1Syy4S02imTlfldA5Dxnrw45joUCALYXF3s_rFk4SVYC293oPrcCtbH1J-N2KxS9HyvWX0VWGssQ2VcUcpg
      JobName: minio-job
      MetricsPath: /minio/v2/metrics/cluster
      Scheme: https
      StaticConfigs:
      - Targets:
        - minio.tenant1.svc.cluster.local:443
      TLSConfig:
        CAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-01T14:07:02Z"
  name: tenant1-prometheus-config-map
  namespace: tenant1
  ownerReferences:
  - apiVersion: minio.min.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: tenant1
    uid: 0a5c90aa-44a7-4ec9-80b1-e2236ae0b35d
  resourceVersion: "160755"
  uid: e2aea3cb-7119-42e0-b4eb-5314220bb8d1
```

2022-02-01 17:32 UTC, harshavardhana commented
> @harshavardhana prometheus is failing with following error
> 
> ```
> ts=2022-02-01T14:10:12.900Z caller=main.go:434 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" err="parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 4: field Global not found in type config.plain\n  line 7: field ScrapeConfigs not found in type config.plain"
> ```
> 
> ```
> apiVersion: v1
> data:
>   prometheus.yml: |
>     # This file and config-map is generated by MinIO Operator.
>     # DO NOT EDIT.
> 
>     Global:
>       EvaluationInterval: 30000000000
>       ScrapeInterval: 30000000000
>     ScrapeConfigs:
>     - BearerToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ3OTczMjQ0MjIsImlzcyI6InByb21ldGhldXMiLCJzdWIiOiIwSUkwS0lMVjJLWldZVFFKIn0.GUY1Syy4S02imTlfldA5Dxnrw45joUCALYXF3s_rFk4SVYC293oPrcCtbH1J-N2KxS9HyvWX0VWGssQ2VcUcpg
>       JobName: minio-job
>       MetricsPath: /minio/v2/metrics/cluster
>       Scheme: https
>       StaticConfigs:
>       - Targets:
>         - minio.tenant1.svc.cluster.local:443
>       TLSConfig:
>         CAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
> kind: ConfigMap
> metadata:
>   creationTimestamp: "2022-02-01T14:07:02Z"
>   name: tenant1-prometheus-config-map
>   namespace: tenant1
>   ownerReferences:
>   - apiVersion: minio.min.io/v2
>     blockOwnerDeletion: true
>     controller: true
>     kind: Tenant
>     name: tenant1
>     uid: 0a5c90aa-44a7-4ec9-80b1-e2236ae0b35d
>   resourceVersion: "160755"
>   uid: e2aea3cb-7119-42e0-b4eb-5314220bb8d1
> ```

Yes thanks @kanagarajkm this is what I was chasing.

2022-02-01 19:55 UTC, Alevsk approved these changes

2022-02-01 19:55 UTC, Alevsk commented on kubectl-minio/cmd/proxy.go
> +		// fmt.Printf("\nout:\n%s\nerr:\n%s\n", outStr, errStr)
we can delete commented code

2022-02-01 19:55 UTC, Alevsk commented on pkg/controller/cluster/http_handlers.go
> +			// tenantV1 := obj.Object.(*miniov1.Tenant)
delete commented code

2022-02-01 19:55 UTC, Alevsk commented on pkg/controller/cluster/main-controller.go
> +	// addingNewPool := len(tenant.Spec.Pools) == len(tenant.Status.Pools)
delete commented code

2022-02-01 20:38 UTC, dvaldivia approved these changes

2022-02-01 20:38 UTC, merged